const COLLECTIONS=['outfits','perfumes','archetypes','hairstyles','garments','wears','plans','wishlist','trips'];
const APP_ID=window.ARCHIVE_APP_ID||'the-archive-antwerp';
const FIREBASE_CONFIG=window.ARCHIVE_FIREBASE_CONFIG||null;
const storageKey=(type)=>`archive:v9:${APP_ID}:${type}`;
function localRead(type){try{return JSON.parse(localStorage.getItem(storageKey(type))||'[]')}catch{return []}}
function localWrite(type,items){localStorage.setItem(storageKey(type),JSON.stringify(items));window.dispatchEvent(new CustomEvent('archive-local-change',{detail:{type}}));}
function mergeItems(current,incoming){const map=new Map(current.map(item=>[String(item.id||item.name),item]));incoming.forEach(item=>map.set(String(item.id||item.name),item));return Array.from(map.values());}
async function createLocalAdapter(){return{mode:'local',async init(){return{uid:'local-device'}},subscribe(type,cb){const emit=()=>cb(localRead(type));emit();const c=e=>{if(e.detail?.type===type)emit()},s=e=>{if(e.key===storageKey(type))emit()};window.addEventListener('archive-local-change',c);window.addEventListener('storage',s);return()=>{window.removeEventListener('archive-local-change',c);window.removeEventListener('storage',s)}},async saveItems(type,items){localWrite(type,mergeItems(localRead(type),items))},async replace(type,items){localWrite(type,items)},async wipe(type){localStorage.removeItem(storageKey(type));window.dispatchEvent(new CustomEvent('archive-local-change',{detail:{type}}));}}}
async function createFirebaseAdapter(config){const[{initializeApp},authMod,fsMod]=await Promise.all([import('https://www.gstatic.com/firebasejs/11.6.1/firebase-app.js'),import('https://www.gstatic.com/firebasejs/11.6.1/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/11.6.1/firebase-firestore.js')]);const app=initializeApp(config),auth=authMod.getAuth(app),db=fsMod.getFirestore(app);const path=t=>fsMod.collection(db,'artifacts',APP_ID,'public','data',t);return{mode:'cloud',async init(){if(window.ARCHIVE_INITIAL_AUTH_TOKEN)await authMod.signInWithCustomToken(auth,window.ARCHIVE_INITIAL_AUTH_TOKEN);else await authMod.signInAnonymously(auth);return new Promise((resolve,reject)=>{const stop=authMod.onAuthStateChanged(auth,u=>{if(u){stop();resolve(u)}},reject)})},subscribe(type,cb){return fsMod.onSnapshot(fsMod.query(path(type)),snap=>cb(snap.docs.map(d=>d.data())))},async saveItems(type,items){for(const item of items){const id=String(item.id||item.name).replace(/\//g,'_');await fsMod.setDoc(fsMod.doc(db,'artifacts',APP_ID,'public','data',type,id),item)}},async replace(type,items){const snap=await fsMod.getDocs(path(type));for(const d of snap.docs)await fsMod.deleteDoc(d.ref);await this.saveItems(type,items)},async wipe(type){const snap=await fsMod.getDocs(path(type));for(const d of snap.docs)await fsMod.deleteDoc(d.ref)}}}
try{const cloud=FIREBASE_CONFIG&&FIREBASE_CONFIG.apiKey&&FIREBASE_CONFIG.projectId;window.ArchiveStorage=cloud?await createFirebaseAdapter(FIREBASE_CONFIG):await createLocalAdapter()}catch(e){console.warn('Cloud unavailable, using local storage.',e);window.ArchiveStorage=await createLocalAdapter()}
window.ARCHIVE_COLLECTIONS=COLLECTIONS;window.dispatchEvent(new Event('archive-storage-ready'));
