(()=>{
const V='13.0.0';
const TOP=['SHIRT','T-SHIRT','POLO','KNITWEAR'],BOTTOM=['TROUSERS','JEANS','SHORTS'],SHOES=['SHOES','BOOTS'],OUTER=['JACKET','OUTERWEAR','SUIT'],ACCESS=['BELT','WATCH','BAG','TIE','POCKET SQUARE','HAT','SCARF','JEWELLERY','GLASSES','ACCESSORY'];
const originalFactory=window.wardrobeApp;
if(!originalFactory)return;
window.wardrobeApp=function(){
  const a=originalFactory();
  a.version=V;
  a.tabs.push({id:'studio',label:'Studio'},{id:'stylist',label:'Stylist'});
  a.relationships=[];a.atelier=[];a.retired=[];a.journals=[];a.styleRules=[];a.outfitFamilies=[];a.locations=[];
  a.garmentStatuses.includes('RETIRED')||a.garmentStatuses.push('RETIRED');
  a.databaseCards.push(
    {type:'relationships',label:'Garment relationships'},{type:'journals',label:'Outfit journal'},
    {type:'atelier',label:'Atelier'},{type:'retired',label:'Retirement archive'},
    {type:'styleRules',label:'Style rules'},{type:'outfitFamilies',label:'Outfit families'},{type:'locations',label:'Wardrobe locations'}
  );
  a.relationshipDraft={a:'',b:'',rating:2,type:'WORKS',note:''};
  a.familyDraft={name:'',baseOutfitId:'',variantOutfitId:'',variantLabel:'CASUAL'};
  a.locationDraft={name:'',zone:'WARDROBE',note:''};a.locationAssign={garmentId:'',locationId:''};
  a.atelierDraft={garmentId:'',issue:'',action:'',tailor:'',cost:'',dueDate:'',before:'',after:'',status:'OPEN',notes:''};
  a.journalDraft={outfitId:'',context:'WORK',appearance:4,comfort:4,confidence:4,practicality:4,temperature:4,fit:4,reaction:'',note:'',photo:''};a.journalPhotoName='';
  a.retireDraft={garmentId:'',reason:'SOLD',date:new Date().toISOString().slice(0,10),amount:'',note:''};
  a.ruleDraft={kind:'PREFER_COLOR',value:'',strength:'SOFT',note:''};
  a.compareA='';a.compareB='';a.capsuleTarget=15;a.capsuleResult=null;
  a.whyNotGarmentId='';
  a.scenario={occasion:'WORK',temp:15,rain:false,walking:2,formality:3,mustWearId:'',note:''};a.scenarioLook=[];
  a.stylistPrompt='';a.stylistResults=[];

  const oldGen=a.garmentGeneratorScore?.bind(a);const oldCompat=a.outfitCompatibility?.bind(a);const oldBlank=a.blankGarment.bind(a);
  a.blankGarment=function(){return {...oldBlank(),locationId:'',retiredAt:'',retirementReason:''};};

  a.activeGarments=function(){return this.garments.filter(g=>g.status!=='RETIRED');};
  a.locationName=function(id){return this.locations.find(x=>x.id===id)?.name||'Unassigned';};
  a.journalsForGarment=function(id){return this.journals.filter(j=>(j.garmentIds||[]).includes(id));};
  a.journalsForOutfit=function(id){return this.journals.filter(j=>j.outfitId===id);};
  a.avg=function(arr){const n=arr.filter(x=>Number.isFinite(+x)).map(Number);return n.length?n.reduce((s,x)=>s+x,0)/n.length:0;};

  a.relationshipBetween=function(id1,id2){return this.relationships.find(r=>(r.a===id1&&r.b===id2)||(r.a===id2&&r.b===id1))||null;};
  a.relationshipValue=function(id1,id2){const r=this.relationshipBetween(id1,id2);return r?Math.max(-2,Math.min(2,+r.rating||0)):0;};
  a.relationshipSummary=function(g){
    const rs=this.relationships.filter(r=>r.a===g.id||r.b===g.id);return {great:rs.filter(r=>(+r.rating||0)>=2).length,avoid:rs.filter(r=>(+r.rating||0)<=-1).length,total:rs.length};
  };
  a.saveRelationship=async function(){
    const d=this.relationshipDraft;if(!d.a||!d.b||d.a===d.b)return this.toast('Choose two different garments');
    const existing=this.relationshipBetween(d.a,d.b);await this.save('relationships',[{id:existing?.id||this.uid('REL'),a:d.a,b:d.b,rating:+d.rating,type:d.type,note:d.note,updatedAt:new Date().toISOString()}]);
    this.relationshipDraft={a:'',b:'',rating:2,type:'WORKS',note:''};this.toast('Relationship learned');
  };
  a.pairRelationshipScore=function(gs){let sum=0,n=0;for(let i=0;i<gs.length;i++)for(let j=i+1;j<gs.length;j++){sum+=this.relationshipValue(gs[i].id,gs[j].id);n++;}return n?sum/n:0;};

  a.styleRuleGarmentAdjustment=function(g){let s=0;for(const r of this.styleRules.filter(x=>x.enabled!==false)){
    const v=String(r.value||'').toUpperCase(),hard=r.strength==='HARD'?2:1,yes=(kind)=>String(r.kind||'')===kind;
    if(yes('PREFER_COLOR')&&(g.color||'').toUpperCase().includes(v))s+=12*hard;
    if(yes('AVOID_COLOR')&&(g.color||'').toUpperCase().includes(v))s-=20*hard;
    if(yes('PREFER_CATEGORY')&&g.category===v)s+=12*hard;if(yes('AVOID_CATEGORY')&&g.category===v)s-=24*hard;
    if(yes('PREFER_MATERIAL')&&(g.material||'').toUpperCase().includes(v))s+=10*hard;if(yes('AVOID_MATERIAL')&&(g.material||'').toUpperCase().includes(v))s-=18*hard;
    if(yes('PREFER_TAG')&&(g.tags||[]).includes(v))s+=12*hard;if(yes('AVOID_TAG')&&(g.tags||[]).includes(v))s-=20*hard;
  }return s;};
  a.styleRulePairAdjustment=function(gs){let s=0;for(const r of this.styleRules.filter(x=>x.enabled!==false&&['PAIR_AVOID','PAIR_PREFER'].includes(x.kind))){
    const parts=String(r.value||'').toUpperCase().split(/[;+]/).map(x=>x.trim()).filter(Boolean);if(parts.length<2)continue;
    const text=gs.map(g=>`${g.category} ${g.color||''} ${g.material||''} ${(g.tags||[]).join(' ')}`).join(' | ').toUpperCase();
    if(parts.every(p=>text.includes(p)))s+=(r.kind==='PAIR_PREFER'?12:-20)*(r.strength==='HARD'?2:1);
  }return s;};
  a.contextGarmentAdjustment=function(g){
    const ctx=this.generator.occasion||'WORK';const js=this.journals.filter(j=>j.context===ctx&&(j.garmentIds||[]).includes(g.id));if(!js.length)return 0;
    const score=this.avg(js.map(j=>this.avg([j.appearance,j.comfort,j.confidence,j.practicality,j.temperature,j.fit])));return (score-3)*6;
  };
  if(oldGen)a.garmentGeneratorScore=function(g){return oldGen(g)+this.styleRuleGarmentAdjustment(g)+this.contextGarmentAdjustment(g);};
  if(oldCompat)a.outfitCompatibility=function(gs,...rest){const r=oldCompat(gs,...rest),rel=this.pairRelationshipScore(gs),rules=this.styleRulePairAdjustment(gs);return {...r,relationships:Math.round(50+rel*25),total:this.clamp(Math.round(r.total+rel*5+rules*.35),0,100)};};

  a.recommendationConfidence=function(gs=this.generatedLook){
    if(!gs?.length)return 0;const c=this.outfitCompatibility(gs,this.generator.season,this.generator.occasion),known=gs.filter(g=>this.garmentWearCount(g.id)>0).length/gs.length,
      feedback=this.avg(gs.map(g=>Math.max(-1,Math.min(1,this.garmentFeedbackScore(g.id))))),rel=this.pairRelationshipScore(gs),fit=this.bodyProfileComplete?gs.filter(g=>this.fitAssessment(g).score!==null).length/gs.length:.35;
    return this.clamp(Math.round(c.total*.55+known*18+(feedback+1)*7+Math.max(0,rel)*6+fit*7),0,100);
  };

  a.saveStyleRule=async function(){const d=this.ruleDraft;if(!d.value.trim())return;await this.save('styleRules',[{id:this.uid('RULE'),...d,value:d.value.trim(),enabled:true,createdAt:new Date().toISOString()}]);this.ruleDraft={kind:'PREFER_COLOR',value:'',strength:'SOFT',note:''};this.toast('Style rule added');};
  a.toggleRule=async function(r){await this.save('styleRules',[{...r,enabled:r.enabled===false,true:true,enabled:r.enabled===false?true:false}]);};
  a.deleteRule=async function(r){await this.replace('styleRules',this.styleRules.filter(x=>x.id!==r.id));};

  a.addLocation=async function(){if(!this.locationDraft.name.trim())return;await this.save('locations',[{id:this.uid('LOC'),...this.locationDraft,name:this.locationDraft.name.trim()}]);this.locationDraft={name:'',zone:'WARDROBE',note:''};};
  a.assignLocation=async function(){const g=this.garments.find(x=>x.id===this.locationAssign.garmentId);if(!g)return;await this.save('garments',[{...g,locationId:this.locationAssign.locationId,updatedAt:new Date().toISOString()}]);this.toast('Location assigned');};

  a.addFamily=async function(){const d=this.familyDraft;if(!d.name.trim()||!d.baseOutfitId)return;await this.save('outfitFamilies',[{id:this.uid('FAM'),name:d.name.trim(),baseOutfitId:d.baseOutfitId,variants:[],createdAt:new Date().toISOString()}]);this.familyDraft={name:'',baseOutfitId:'',variantOutfitId:'',variantLabel:'CASUAL'};};
  a.addFamilyVariant=async function(f){if(!this.familyDraft.variantOutfitId)return;const variants=[...(f.variants||[]),{label:(this.familyDraft.variantLabel||'VARIANT').toUpperCase(),outfitId:this.familyDraft.variantOutfitId}];await this.save('outfitFamilies',[{...f,variants}]);this.familyDraft.variantOutfitId='';};
  a.familyOutfitName=function(id){return this.outfits.find(o=>o.id===id)?.name||'Missing outfit';};

  a.addAtelierTask=async function(){const d=this.atelierDraft;if(!d.garmentId||!d.issue.trim())return;await this.save('atelier',[{id:this.uid('ATEL'),...d,cost:d.cost?+d.cost:null,createdAt:new Date().toISOString()}]);this.atelierDraft={garmentId:'',issue:'',action:'',tailor:'',cost:'',dueDate:'',before:'',after:'',status:'OPEN',notes:''};this.toast('Atelier task opened');};
  a.completeAtelier=async function(t){await this.save('atelier',[{...t,status:'DONE',completedAt:new Date().toISOString()}]);this.toast('Alteration archived');};
  a.atelierGarment=function(t){return this.garments.find(g=>g.id===t.garmentId)||this.retired.find(r=>r.garmentId===t.garmentId)?.snapshot||null;};

  a.handleJournalPhoto=async function(e){const f=e.target.files?.[0];if(!f)return;this.journalPhotoName=f.name;this.journalDraft.photo=await this.compressImage(f,900,.72);e.target.value='';};
  a.saveJournal=async function(){const d=this.journalDraft;if(!d.outfitId)return;const o=this.outfits.find(x=>x.id===d.outfitId),gs=o?this.outfitGarments(o):[];
    await this.save('journals',[{id:this.uid('JRNL'),date:this.today(),...d,garmentIds:gs.map(g=>g.id),weather:{temp:this.weather.temp,condition:this.weather.condition,tags:this.weatherTags},createdAt:new Date().toISOString()}]);
    this.journalDraft={outfitId:'',context:'WORK',appearance:4,comfort:4,confidence:4,practicality:4,temperature:4,fit:4,reaction:'',note:'',photo:''};this.journalPhotoName='';this.toast('Wear journal saved');};
  a.journalScore=function(j){return this.avg([j.appearance,j.comfort,j.confidence,j.practicality,j.temperature,j.fit]);};

  a.seasonalAction=function(g){const cur=this.currentSeason(),seasons=g.seasons||[];if(g.status==='RETIRED')return'RETIRED';if(seasons.includes(cur))return'ACTIVE';
    const order=['WINTER','SPRING','SUMMER','AUTUMN'],i=order.indexOf(cur),next=order[(i+1)%4];if(seasons.includes(next))return'TRANSITION';return'STORE';};
  a.getSeasonalLists=function(){return {active:this.activeGarments().filter(g=>this.seasonalAction(g)==='ACTIVE'),transition:this.activeGarments().filter(g=>this.seasonalAction(g)==='TRANSITION'),store:this.activeGarments().filter(g=>this.seasonalAction(g)==='STORE')};};

  a.rediscover=function(){const pool=this.activeGarments().filter(g=>['AVAILABLE','WORN'].includes(g.status)).sort((x,y)=>this.daysSinceGarmentWorn(y.id)-this.daysSinceGarmentWorn(x.id));if(!pool.length)return;
    const hero=pool[0],role=this.garmentRole(hero),rank=this.rankedGarmentsForGenerator(),look=[hero];for(const cats of [TOP,BOTTOM,SHOES,OUTER,ACCESS]){const dummy={category:cats[0]},r=this.garmentRole(dummy);if(r===role)continue;const c=rank.filter(g=>cats.includes(g.category)&&g.id!==hero.id).sort((x,y)=>this.outfitCompatibility([...look,y],this.currentSeason(),this.generator.occasion).total-this.outfitCompatibility([...look,x],this.currentSeason(),this.generator.occasion).total)[0];if(c)look.push(c);}this.generatedLook=look;this.generatedScore=this.outfitCompatibility(look,this.currentSeason(),this.generator.occasion).total;this.generatedExplanation=this.buildRecommendationExplanation(look);this.currentView='today';this.toast(`Rediscovered ${hero.name}`);};

  a.retireGarment=async function(){const d=this.retireDraft,g=this.garments.find(x=>x.id===d.garmentId);if(!g)return;const rec={id:this.uid('RET'),garmentId:g.id,reason:d.reason,date:d.date,amount:d.amount?+d.amount:null,note:d.note,snapshot:{...g},lifetimeWears:this.garmentWearCount(g.id),lifetimeCpw:this.costPerWear(g),createdAt:new Date().toISOString()};await this.save('retired',[rec]);await this.save('garments',[{...g,status:'RETIRED',retiredAt:d.date,retirementReason:d.reason}]);this.retireDraft={garmentId:'',reason:'SOLD',date:this.today(),amount:'',note:''};this.toast(`${g.name} moved to retirement archive`);};

  a.garmentSimilarity=function(x,y){if(!x||!y||x.id===y.id)return 0;let s=0;if(x.category===y.category)s+=38;if((x.color||'').toUpperCase()===(y.color||'').toUpperCase())s+=22;else if(this.pairColorScore(x.colorHex,y.colorHex)>85)s+=12;if((x.material||'')&&(y.material||'')&&x.material.toUpperCase()===y.material.toUpperCase())s+=18;if(Math.abs((+x.formality||3)-(+y.formality||3))<=1)s+=12;const sx=new Set(x.seasons||[]),sy=new Set(y.seasons||[]);if([...sx].some(v=>sy.has(v)))s+=10;return this.clamp(s,0,100);};
  Object.defineProperty(a,'redundancyPairs',{get(){const arr=[];const gs=this.activeGarments();for(let i=0;i<gs.length;i++)for(let j=i+1;j<gs.length;j++){const score=this.garmentSimilarity(gs[i],gs[j]);if(score>=70)arr.push({a:gs[i],b:gs[j],score});}return arr.sort((x,y)=>y.score-x.score).slice(0,20);}});

  a.purchaseMetrics=function(w){if(!w)return null;return {name:w.name,compat:this.wishCompatibilityCount(w),unlock:this.wishUnlockScore(w),gap:this.wishlistGapScore(w),price:+w.price||0,redundancy:this.garments.filter(g=>g.category===w.category&&this.pairColorScore(g.colorHex,w.colorHex||'#777')>80).length};};
  Object.defineProperty(a,'purchaseComparison',{get(){return {a:this.purchaseMetrics(this.wishlist.find(w=>w.id===this.compareA)),b:this.purchaseMetrics(this.wishlist.find(w=>w.id===this.compareB))};}});

  a.optimiseCapsule=function(){const target=Math.max(1,+this.capsuleTarget||15),gs=this.activeGarments().filter(g=>['AVAILABLE','WORN'].includes(g.status)),groups={top:gs.filter(g=>TOP.includes(g.category)),bottom:gs.filter(g=>BOTTOM.includes(g.category)),shoe:gs.filter(g=>SHOES.includes(g.category)),outer:gs.filter(g=>OUTER.includes(g.category))};let best=null;
    for(let t=1;t<=Math.min(6,groups.top.length);t++)for(let b=1;b<=Math.min(5,groups.bottom.length);b++)for(let s=1;s<=Math.min(3,groups.shoe.length);s++)for(let o=0;o<=Math.min(2,groups.outer.length);o++){const combos=t*b*s*Math.max(1,o);const pieces=t+b+s+o;if(combos>=target&&(!best||pieces<best.pieces||(pieces===best.pieces&&combos>best.combos)))best={t,b,s,o,pieces,combos};}
    if(!best)return this.toast('Not enough category coverage for target');const rank=x=>this.garmentGeneratorScore(x);const take=(arr,n)=>[...arr].sort((x,y)=>rank(y)-rank(x)).slice(0,n);const chosen=[...take(groups.top,best.t),...take(groups.bottom,best.b),...take(groups.shoe,best.s),...take(groups.outer,best.o)];this.capsuleResult={...best,garments:chosen};};

  a.monthKey=function(date){return (date||'').slice(0,7);};
  Object.defineProperty(a,'styleEvolution',{get(){const months=[];for(let i=5;i>=0;i--){const d=new Date();d.setMonth(d.getMonth()-i);const key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`,wears=this.wears.filter(w=>this.monthKey(w.date)===key),ids=new Set(wears.flatMap(w=>w.garmentIds||[])),gs=[...ids].map(id=>this.garments.find(g=>g.id===id)).filter(Boolean),formality=this.avg(gs.map(g=>+g.formality||3)),colors={};gs.forEach(g=>{const c=g.color||'Unknown';colors[c]=(colors[c]||0)+1;});const topColor=Object.entries(colors).sort((x,y)=>y[1]-x[1])[0]?.[0]||'—';months.push({key,wears:wears.length,formality:formality?formality.toFixed(1):'—',topColor});}return months;}});

  Object.defineProperty(a,'wardrobeHealth',{get(){const gs=this.activeGarments(),n=Math.max(1,gs.length),rotation=Math.round(gs.filter(g=>this.daysSinceGarmentWorn(g.id)<=90).length/n*100),maintenance=Math.round(gs.filter(g=>!this.garmentCareDue(g)).length/n*100),redundancy=Math.max(0,100-Math.min(70,this.redundancyPairs.length*7)),core=['SHIRT','TROUSERS','SHOES','JACKET'],coverage=Math.round(core.reduce((s,c)=>s+Math.min(1,gs.filter(g=>g.category===c).length/2),0)/core.length*100),fit=this.bodyProfileComplete?Math.round(gs.filter(g=>this.fitAssessment(g).score!==null).length/n*100):35,cost=Math.round(gs.filter(g=>this.garmentWearCount(g.id)>0).length/n*100),total=Math.round(rotation*.25+maintenance*.2+redundancy*.15+coverage*.15+fit*.1+cost*.15);return{total,rotation,maintenance,redundancy,coverage,fit,cost};}});

  a.whyNot=function(g){if(!g)return[];const out=[];if(this.generatedLook.some(x=>x.id===g.id))return['It is already in the current recommendation.'];if(!['AVAILABLE','WORN'].includes(g.status))out.push(`Status is ${g.status}.`);if((g.seasons||[]).length&&!(g.seasons||[]).includes(this.generator.season))out.push(`Not tagged for ${this.generator.season}.`);const tags=this.weatherTags;if(tags.includes('RAIN')&&!g.waterproof)out.push('Current conditions favour rain-safe pieces.');if(tags.includes('COLD')&&(+g.warmth||3)<3)out.push('Warmth score is low for current conditions.');if(tags.includes('HOT')&&(+g.warmth||3)>3)out.push('Likely too warm for current conditions.');if(this.garmentRecencyPenalty(g.id)>5)out.push('Recently worn, so rotation logic pushed it down.');if(this.garmentFeedbackScore(g.id)<-.2)out.push('Past feedback is currently negative.');if(this.styleRuleGarmentAdjustment(g)<0)out.push('One or more explicit style rules penalise it.');const role=this.garmentRole(g),selected=this.generatedLook.find(x=>this.garmentRole(x)===role);if(selected){const a=this.garmentGeneratorScore(g),b=this.garmentGeneratorScore(selected);if(b>a)out.push(`${selected.name} scored ${Math.round(b-a)} points higher for this context.`);}return out.length?out:['It was a close alternative; another piece ranked marginally higher.'];};
  Object.defineProperty(a,'whyNotResult',{get(){return this.whyNot(this.garments.find(g=>g.id===this.whyNotGarmentId));}});

  a.scenarioGenerate=function(){const sc=this.scenario,available=this.activeGarments().filter(g=>['AVAILABLE','WORN'].includes(g.status)),score=g=>{let s=40;if((g.tags||[]).includes(sc.occasion))s+=22;if(Math.abs((+g.formality||3)-(+sc.formality||3))<=1)s+=15;if(sc.rain&&g.waterproof)s+=22;if(sc.temp<=10)s+=(+g.warmth||3)*6;if(sc.temp>=24)s+=(6-(+g.warmth||3))*6;if(sc.walking>=5&&SHOES.includes(g.category)&&(g.tags||[]).some(t=>/WALK|COMFORT|TRAVEL/.test(t)))s+=18;s+=this.styleRuleGarmentAdjustment(g);return s;};const sorted=[...available].sort((x,y)=>score(y)-score(x)),must=available.find(g=>g.id===sc.mustWearId),look=must?[must]:[],used=new Set(look.map(g=>g.id));for(const cats of [TOP,BOTTOM,SHOES,OUTER,ACCESS]){if(look.some(g=>cats.includes(g.category)))continue;const g=sorted.find(x=>cats.includes(x.category)&&!used.has(x.id));if(g){look.push(g);used.add(g.id);}}this.scenarioLook=look;};

  a.parseStylistPrompt=function(q){const t=q.toLowerCase(),occasion=t.includes('interview')?'INTERVIEW':t.includes('date')?'DATE':t.includes('dinner')||t.includes('night')?'NIGHT OUT':t.includes('travel')?'TRAVEL':t.includes('casual')?'CASUAL':'WORK',rain=/rain|wet|shower/.test(t),hot=/hot|warm|summer/.test(t),cold=/cold|winter|chilly/.test(t);let temp=this.weather.temp??15;const m=t.match(/(-?\d{1,2})\s*°?/);if(m)temp=+m[1];else if(hot)temp=27;else if(cold)temp=7;const must=this.activeGarments().find(g=>t.includes((g.name||'').toLowerCase()));return{occasion,rain,temp,must};};
  a.stylistBuild=function(seed,ctx){const gs=this.activeGarments().filter(g=>['AVAILABLE','WORN'].includes(g.status)),score=g=>{let s=this.garmentGeneratorScore(g);if((g.tags||[]).includes(ctx.occasion))s+=20;if(ctx.rain&&g.waterproof)s+=22;if(ctx.temp<=10)s+=(+g.warmth||3)*4;if(ctx.temp>=24)s+=(6-(+g.warmth||3))*4;return s;},rank=[...gs].sort((x,y)=>score(y)-score(x)),look=ctx.must?[ctx.must]:[],used=new Set(look.map(g=>g.id));for(const cats of [TOP,BOTTOM,SHOES,OUTER,ACCESS]){if(look.some(g=>cats.includes(g.category)))continue;const c=rank.filter(g=>cats.includes(g.category)&&!used.has(g.id)).slice(seed,seed+4)[0]||rank.find(g=>cats.includes(g.category)&&!used.has(g.id));if(c){look.push(c);used.add(c.id);}}return look;};
  a.askStylist=function(){const q=this.stylistPrompt.trim();if(!q)return;const ctx=this.parseStylistPrompt(q);this.stylistResults=[0,1,2].map((seed,i)=>{const look=this.stylistBuild(seed,ctx),score=this.outfitCompatibility(look,this.currentSeason(),ctx.occasion).total;return{id:i+1,look,score,confidence:this.recommendationConfidence(look),reason:[`${ctx.occasion} scenario`,ctx.rain?'Rain-aware':'Weather-neutral',ctx.must?`Keeps ${ctx.must.name}`:'Built from available wardrobe']};});};
  a.useStylistLook=function(r){this.generatedLook=[...r.look];this.generatedScore=r.score;this.generatedExplanation=this.buildRecommendationExplanation(r.look);this.currentView='today';};

  return a;
};

function studioUI(){return `
<section x-show="currentView==='studio'" x-cloak class="v13-space">
  <div class="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><div class="eyebrow">Deep wardrobe systems · v13</div><h2 class="section-title mt-1">Studio</h2><p class="text-sm muted mt-2">Relationships, memory, maintenance, lifecycle and wardrobe optimisation.</p></div><button class="btn btn-primary" @click="rediscover()">Rediscover my wardrobe</button></div>
  <div class="v13-grid mt-5">
    <article class="card p-5"><div class="eyebrow">Wardrobe health</div><div class="metric mt-2" x-text="wardrobeHealth.total"></div><div class="v13-bars mt-4"><template x-for="x in [{n:'Rotation',v:wardrobeHealth.rotation},{n:'Maintenance',v:wardrobeHealth.maintenance},{n:'Redundancy',v:wardrobeHealth.redundancy},{n:'Coverage',v:wardrobeHealth.coverage},{n:'Fit data',v:wardrobeHealth.fit},{n:'Cost use',v:wardrobeHealth.cost}]" :key="x.n"><div><div class="flex justify-between text-xs"><span x-text="x.n"></span><span x-text="x.v"></span></div><div class="bar mt-1"><span :style="\`width:${x.v}%\`"></span></div></div></template></div></article>
    <article class="card p-5"><div class="eyebrow">Why not?</div><h3 class="serif text-xl mt-1">Explain a rejected garment</h3><select class="field mt-3" x-model="whyNotGarmentId"><option value="">Choose garment…</option><template x-for="g in activeGarments()" :key="g.id"><option :value="g.id" x-text="g.name"></option></template></select><div class="mt-3 space-y-2"><template x-for="r in whyNotResult" :key="r"><div class="v13-reason" x-text="r"></div></template></div></article>
    <article class="card p-5"><div class="eyebrow">Relationship graph</div><div class="grid gap-2 mt-3"><select class="field" x-model="relationshipDraft.a"><option value="">Piece A…</option><template x-for="g in activeGarments()"><option :value="g.id" x-text="g.name"></option></template></select><select class="field" x-model="relationshipDraft.b"><option value="">Piece B…</option><template x-for="g in activeGarments()"><option :value="g.id" x-text="g.name"></option></template></select><select class="field" x-model.number="relationshipDraft.rating"><option :value="2">Excellent</option><option :value="1">Works</option><option :value="0">Neutral</option><option :value="-1">Avoid</option><option :value="-2">Never pair</option></select><input class="field" x-model="relationshipDraft.note" placeholder="Why / when"><button class="btn btn-primary" @click="saveRelationship()">Learn pairing</button></div><div class="text-xs muted mt-3"><span x-text="relationships.length"></span> explicit garment relationships learned.</div></article>
    <article class="card p-5"><div class="eyebrow">Personal style rules</div><div class="grid gap-2 mt-3"><select class="field" x-model="ruleDraft.kind"><option>PREFER_COLOR</option><option>AVOID_COLOR</option><option>PREFER_CATEGORY</option><option>AVOID_CATEGORY</option><option>PREFER_MATERIAL</option><option>AVOID_MATERIAL</option><option>PREFER_TAG</option><option>AVOID_TAG</option><option>PAIR_PREFER</option><option>PAIR_AVOID</option></select><input class="field" x-model="ruleDraft.value" placeholder="BLACK or SHOES+TAILORED"><select class="field" x-model="ruleDraft.strength"><option>SOFT</option><option>HARD</option></select><input class="field" x-model="ruleDraft.note" placeholder="Rule note"><button class="btn btn-primary" @click="saveStyleRule()">Add rule</button></div><div class="mt-3 space-y-2"><template x-for="r in styleRules" :key="r.id"><div class="card-soft p-2 flex justify-between gap-2"><div><span class="pill" x-text="r.strength"></span><span class="text-xs ml-2" x-text="r.kind+' · '+r.value"></span></div><button class="text-xs muted" @click="deleteRule(r)">×</button></div></template></div></article>
    <article class="card p-5"><div class="eyebrow">Outfit journal</div><div class="grid gap-2 mt-3"><select class="field" x-model="journalDraft.outfitId"><option value="">Outfit…</option><template x-for="o in outfits"><option :value="o.id" x-text="o.name"></option></template></select><select class="field" x-model="journalDraft.context"><template x-for="o in occasions"><option x-text="o"></option></template></select><div class="grid grid-cols-3 gap-2 text-xs"><label>Appearance<input class="field mt-1" type="number" min="1" max="5" x-model.number="journalDraft.appearance"></label><label>Comfort<input class="field mt-1" type="number" min="1" max="5" x-model.number="journalDraft.comfort"></label><label>Confidence<input class="field mt-1" type="number" min="1" max="5" x-model.number="journalDraft.confidence"></label><label>Practical<input class="field mt-1" type="number" min="1" max="5" x-model.number="journalDraft.practicality"></label><label>Temperature<input class="field mt-1" type="number" min="1" max="5" x-model.number="journalDraft.temperature"></label><label>Fit<input class="field mt-1" type="number" min="1" max="5" x-model.number="journalDraft.fit"></label></div><input class="field" x-model="journalDraft.reaction" placeholder="Compliments / reactions"><textarea class="field" x-model="journalDraft.note" placeholder="What actually worked?"></textarea><label class="btn text-center">Wear photo<input class="hidden-file" type="file" accept="image/*" capture="environment" @change="handleJournalPhoto($event)"></label><button class="btn btn-primary" @click="saveJournal()">Archive wear experience</button></div><div class="text-xs muted mt-3"><span x-text="journals.length"></span> detailed wear journals.</div></article>
    <article class="card p-5"><div class="eyebrow">Atelier</div><div class="grid gap-2 mt-3"><select class="field" x-model="atelierDraft.garmentId"><option value="">Garment…</option><template x-for="g in activeGarments()"><option :value="g.id" x-text="g.name"></option></template></select><input class="field" x-model="atelierDraft.issue" placeholder="Issue"><input class="field" x-model="atelierDraft.action" placeholder="Alteration / repair"><div class="grid grid-cols-2 gap-2"><input class="field" x-model="atelierDraft.tailor" placeholder="Tailor"><input class="field" type="number" x-model="atelierDraft.cost" placeholder="Cost €"></div><div class="grid grid-cols-2 gap-2"><input class="field" x-model="atelierDraft.before" placeholder="Before measurement"><input class="field" x-model="atelierDraft.after" placeholder="Target / after"></div><button class="btn btn-primary" @click="addAtelierTask()">Open task</button></div><div class="mt-3 space-y-2"><template x-for="t in atelier.filter(x=>x.status!=='DONE').slice(0,5)" :key="t.id"><div class="card-soft p-2"><div class="serif" x-text="atelierGarment(t)?.name||'Garment'"></div><div class="text-xs muted" x-text="t.issue+' · '+t.action"></div><button class="btn mt-2" @click="completeAtelier(t)">Complete</button></div></template></div></article>
    <article class="card p-5"><div class="eyebrow">Wardrobe locations</div><div class="grid gap-2 mt-3"><input class="field" x-model="locationDraft.name" placeholder="Bedroom · left rail"><select class="field" x-model="locationDraft.zone"><option>WARDROBE</option><option>DRAWER</option><option>SHELF</option><option>BOX</option><option>SHOE RACK</option><option>OTHER</option></select><button class="btn" @click="addLocation()">Add location</button><div class="rule my-1"></div><select class="field" x-model="locationAssign.garmentId"><option value="">Garment…</option><template x-for="g in activeGarments()"><option :value="g.id" x-text="g.name"></option></template></select><select class="field" x-model="locationAssign.locationId"><option value="">Unassigned</option><template x-for="l in locations"><option :value="l.id" x-text="l.name"></option></template></select><button class="btn btn-primary" @click="assignLocation()">Assign</button></div></article>
    <article class="card p-5"><div class="eyebrow">Outfit families</div><div class="grid gap-2 mt-3"><input class="field" x-model="familyDraft.name" placeholder="Charcoal office system"><select class="field" x-model="familyDraft.baseOutfitId"><option value="">Base outfit…</option><template x-for="o in outfits"><option :value="o.id" x-text="o.name"></option></template></select><button class="btn" @click="addFamily()">Create family</button></div><div class="mt-3 space-y-3"><template x-for="f in outfitFamilies" :key="f.id"><div class="card-soft p-3"><div class="serif text-lg" x-text="f.name"></div><div class="text-xs muted" x-text="'Base · '+familyOutfitName(f.baseOutfitId)"></div><div class="flex flex-wrap gap-1 mt-2"><template x-for="v in f.variants||[]"><span class="pill" x-text="v.label+' · '+familyOutfitName(v.outfitId)"></span></template></div><div class="grid grid-cols-[1fr_100px_auto] gap-2 mt-2"><select class="field" x-model="familyDraft.variantOutfitId"><option value="">Variant…</option><template x-for="o in outfits"><option :value="o.id" x-text="o.name"></option></template></select><input class="field" x-model="familyDraft.variantLabel" placeholder="RAIN"><button class="btn" @click="addFamilyVariant(f)">+</button></div></div></template></div></article>
    <article class="card p-5"><div class="eyebrow">Seasonal rotation</div><div class="grid grid-cols-3 gap-3 mt-3"><div><div class="metric-sm" x-text="getSeasonalLists().active.length"></div><div class="label">Active</div></div><div><div class="metric-sm" x-text="getSeasonalLists().transition.length"></div><div class="label">Transition</div></div><div><div class="metric-sm" x-text="getSeasonalLists().store.length"></div><div class="label">Store</div></div></div><div class="text-xs muted mt-3">Calculated automatically from each garment's season tags and the current season.</div></article>
    <article class="card p-5"><div class="eyebrow">Retirement archive</div><div class="grid gap-2 mt-3"><select class="field" x-model="retireDraft.garmentId"><option value="">Garment…</option><template x-for="g in activeGarments()"><option :value="g.id" x-text="g.name"></option></template></select><select class="field" x-model="retireDraft.reason"><option>SOLD</option><option>DONATED</option><option>WORN OUT</option><option>LOST</option><option>REPLACED</option><option>REGRET PURCHASE</option><option>OTHER</option></select><input class="field" type="date" x-model="retireDraft.date"><input class="field" type="number" x-model="retireDraft.amount" placeholder="Sale amount €"><input class="field" x-model="retireDraft.note" placeholder="Reason / note"><button class="btn btn-danger" @click="retireGarment()">Retire without deleting history</button></div><div class="text-xs muted mt-3"><span x-text="retired.length"></span> retired pieces preserved.</div></article>
    <article class="card p-5"><div class="eyebrow">Redundancy detector</div><div class="mt-3 space-y-2"><template x-for="p in redundancyPairs.slice(0,7)" :key="p.a.id+p.b.id"><div class="card-soft p-2"><div class="flex justify-between"><span class="text-xs" x-text="p.a.name+' ↔ '+p.b.name"></span><span class="pill" x-text="p.score+'%'"></span></div></div></template><div class="text-xs muted" x-show="!redundancyPairs.length">No strong duplicates detected.</div></div></article>
    <article class="card p-5"><div class="eyebrow">Purchase comparison</div><div class="grid gap-2 mt-3"><select class="field" x-model="compareA"><option value="">Candidate A…</option><template x-for="w in wishlist"><option :value="w.id" x-text="w.name"></option></template></select><select class="field" x-model="compareB"><option value="">Candidate B…</option><template x-for="w in wishlist"><option :value="w.id" x-text="w.name"></option></template></select></div><div class="grid grid-cols-2 gap-3 mt-3" x-show="purchaseComparison.a||purchaseComparison.b"><template x-for="m in [purchaseComparison.a,purchaseComparison.b]" :key="m?.name"><div class="card-soft p-3" x-show="m"><div class="serif" x-text="m?.name"></div><div class="text-xs mt-2">Compatibility <b x-text="m?.compat"></b></div><div class="text-xs">Unlock <b x-text="m?.unlock"></b></div><div class="text-xs">Gap <b x-text="m?.gap"></b>/10</div><div class="text-xs">Duplicates <b x-text="m?.redundancy"></b></div></div></template></div></article>
    <article class="card p-5"><div class="eyebrow">Capsule optimiser</div><div class="flex gap-2 mt-3"><input class="field" type="number" min="2" x-model.number="capsuleTarget" placeholder="Target outfits"><button class="btn btn-primary" @click="optimiseCapsule()">Optimise</button></div><div x-show="capsuleResult" class="mt-3"><div class="metric-sm" x-text="capsuleResult?.pieces"></div><div class="text-xs muted" x-text="capsuleResult?capsuleResult.combos+' combinations':''"></div><div class="flex flex-wrap gap-1 mt-2"><template x-for="g in capsuleResult?.garments||[]"><span class="pill" x-text="g.name"></span></template></div></div></article>
    <article class="card p-5"><div class="eyebrow">Style evolution · 6 months</div><div class="mt-3 space-y-2"><template x-for="m in styleEvolution" :key="m.key"><div class="grid grid-cols-4 text-xs border-b border-stone-800 pb-2"><span x-text="m.key"></span><span x-text="m.wears+' wears'"></span><span x-text="'F '+m.formality"></span><span x-text="m.topColor"></span></div></template></div></article>
    <article class="card p-5"><div class="eyebrow">Scenario planner</div><div class="grid gap-2 mt-3"><select class="field" x-model="scenario.occasion"><template x-for="o in occasions"><option x-text="o"></option></template></select><div class="grid grid-cols-3 gap-2"><input class="field" type="number" x-model.number="scenario.temp" placeholder="°C"><input class="field" type="number" x-model.number="scenario.walking" placeholder="Walk km"><input class="field" type="number" min="1" max="5" x-model.number="scenario.formality" placeholder="Formality"></div><label class="card-soft p-2 text-xs"><input type="checkbox" x-model="scenario.rain"> Rain expected</label><select class="field" x-model="scenario.mustWearId"><option value="">No required piece</option><template x-for="g in activeGarments()"><option :value="g.id" x-text="g.name"></option></template></select><button class="btn btn-primary" @click="scenarioGenerate()">Solve day</button></div><div class="flex flex-wrap gap-1 mt-3"><template x-for="g in scenarioLook"><span class="pill" x-text="g.name"></span></template></div></article>
  </div>
</section>`}
function stylistUI(){return `
<section x-show="currentView==='stylist'" x-cloak>
 <div class="max-w-5xl mx-auto"><div class="eyebrow">Local wardrobe reasoning</div><h2 class="section-title mt-1">Stylist</h2><p class="text-sm muted mt-2">Describe the day naturally. The local engine parses occasion, weather and named garments, then builds from pieces you actually own.</p>
 <div class="card p-5 mt-5"><textarea class="field" rows="4" x-model="stylistPrompt" placeholder="Interview tomorrow, about 14°C and rain. Serious but not corporate. I want to wear my charcoal trousers if possible."></textarea><button class="btn btn-primary mt-3" @click="askStylist()">Build three real options</button></div>
 <div class="grid lg:grid-cols-3 gap-4 mt-5"><template x-for="r in stylistResults" :key="r.id"><article class="card p-4"><div class="flex justify-between"><div><div class="eyebrow" x-text="'Option '+r.id"></div><div class="serif text-2xl mt-1" x-text="r.score+'/100'"></div></div><span class="pill" x-text="r.confidence+'% confidence'"></span></div><div class="grid grid-cols-3 gap-2 mt-4"><template x-for="g in r.look" :key="g.id"><div><div class="thumb cutout"><template x-if="g.cutoutImage||g.image"><img :src="g.cutoutImage||g.image"></template><template x-if="!g.cutoutImage&&!g.image"><div class="photo-placeholder" x-text="g.name.slice(0,1)"></div></template></div><div class="text-[10px] truncate mt-1" x-text="g.name"></div></div></template></div><div class="flex flex-wrap gap-1 mt-3"><template x-for="x in r.reason"><span class="pill" x-text="x"></span></template></div><button class="btn btn-primary w-full mt-4" @click="useStylistLook(r)">Use this look</button></article></template></div>
 </div>
</section>`}

document.addEventListener('alpine:init',()=>{const main=document.querySelector('main');if(main&&!document.getElementById('v13-marker')){const marker=document.createElement('div');marker.id='v13-marker';marker.hidden=true;main.appendChild(marker);main.insertAdjacentHTML('beforeend',studioUI()+stylistUI());}});
})();