function projectWorldPoint(wx,wy,z,fov,bob){
  const dx=wx-state.player.x,dy=wy-state.player.y;
  const ca=Math.cos(state.player.a),sa=Math.sin(state.player.a);
  const forward=dx*ca+dy*sa,right=-dx*sa+dy*ca;
  if(forward<=.28)return null;
  const focal=(w*.5)/Math.tan(fov*.5);
  const sx=w*.5+(right/forward)*focal;
  const scale=h/forward*.78;
  const sy=h*.52+bob+scale*.5-z*scale;
  return{x:sx,y:sy,d:forward,scale};
}
function drawFenceSection(x1,y1,x2,y2,fov,bob){
  const len=Math.hypot(x2-x1,y2-y1),parts=Math.max(1,Math.ceil(len/.65));
  for(let i=0;i<parts;i++){
    const t1=i/parts,t2=(i+1)/parts;
    const ax=x1+(x2-x1)*t1,ay=y1+(y2-y1)*t1,bx=x1+(x2-x1)*t2,by=y1+(y2-y1)*t2;
    const a0=projectWorldPoint(ax,ay,0,fov,bob),a1=projectWorldPoint(ax,ay,.42,fov,bob);
    const b0=projectWorldPoint(bx,by,0,fov,bob),b1=projectWorldPoint(bx,by,.42,fov,bob);
    if(!a0||!a1||!b0||!b1)continue;
    if((a0.x<-30&&b0.x<-30)||(a0.x>w+30&&b0.x>w+30))continue;
    ctx.strokeStyle='rgba(72,70,61,.72)';ctx.lineWidth=1;
    ctx.beginPath();ctx.moveTo(a0.x,a0.y);ctx.lineTo(a1.x,a1.y);ctx.moveTo(b0.x,b0.y);ctx.lineTo(b1.x,b1.y);ctx.stroke();
    for(const z of [.16,.32]){const ar=projectWorldPoint(ax,ay,z,fov,bob),br=projectWorldPoint(bx,by,z,fov,bob);if(ar&&br){ctx.beginPath();ctx.moveTo(ar.x,ar.y);ctx.lineTo(br.x,br.y);ctx.stroke()}}
  }
}
function drawPerimeterFence(fov,bob){drawFenceSection(1,1,15,1,fov,bob);drawFenceSection(1,1,1,15,fov,bob);drawFenceSection(15,1,15,15,fov,bob);drawFenceSection(1,15,7,15,fov,bob);drawFenceSection(9,15,15,15,fov,bob)}
function landmarkColor(b){if(b.id==='clinic')return[121,137,131];if(b.id==='apartments')return[105,102,96];if(b.id==='workshop')return[115,73,55];if(b.id==='chapel')return[78,61,46];if(b.id==='warehouse')return[88,79,68];if(b.id==='fuel')return[99,86,60];return[108,114,102]}
function drawVillageLandmarks(fov,bob,time){const items=BUILDINGS.map(b=>{const cx=(b.x0+b.x1+1)*.5,cy=(b.y0+b.y1+1)*.5;const p=projectWorldPoint(cx,cy,0,fov,bob);return{b,cx,cy,p,dist:Math.hypot(cx-state.player.x,cy-state.player.y)}}).filter(o=>o.p&&o.p.x>-w*.35&&o.p.x<w*1.35).sort((a,b)=>b.dist-a.dist);for(const o of items){const b=o.b,p=o.p;const worldWidth=Math.max(1.4,Math.max(b.x1-b.x0+1,b.y1-b.y0+1)*.78);const bh=Math.max(11,p.scale*b.height),bw=Math.max(12,Math.min(w*.46,p.scale*worldWidth));const bottom=p.y,top=bottom-bh,left=p.x-bw*.5,c=landmarkColor(b);const haze=clamp((o.dist-18)/26,0,.08);ctx.save();ctx.globalAlpha=.98;const rr=Math.round(c[0]*(1-haze)+143*haze),gg=Math.round(c[1]*(1-haze)+151*haze),bb=Math.round(c[2]*(1-haze)+145*haze);ctx.fillStyle='rgb('+rr+','+gg+','+bb+')';ctx.fillRect(Math.round(left),Math.round(top),Math.ceil(bw),Math.ceil(bh));ctx.fillStyle='rgba(31,34,31,.62)';const roofH=Math.max(1,Math.round(bh*.06));if(b.id==='chapel'){ctx.beginPath();ctx.moveTo(p.x,top-bh*.24);ctx.lineTo(left-bw*.05,top+roofH);ctx.lineTo(left+bw*1.05,top+roofH);ctx.closePath();ctx.fill()}else ctx.fillRect(Math.round(left-bw*.03),Math.round(top-roofH),Math.ceil(bw*1.06),roofH+1);const floors=Math.max(1,b.floors),cols=(b.id==='warehouse'||b.id==='workshop')?4:3;ctx.fillStyle='rgba(31,42,42,.76)';for(let fy=0;fy<floors;fy++){const wy=top+bh*(.2+(fy/floors)*.56);for(let wx=0;wx<cols;wx++){const ww=Math.max(1,bw*.10),wh=Math.max(1,bh*.055),xx=left+bw*(.16+wx*(.68/Math.max(1,cols-1)))-ww*.5;ctx.fillRect(Math.round(xx),Math.round(wy),Math.ceil(ww),Math.ceil(wh))}}if(b.id==='clinic'){ctx.fillStyle='rgba(133,50,45,.88)';ctx.fillRect(Math.round(p.x-1),Math.round(top+bh*.18),2,Math.max(2,Math.round(bh*.13)))}ctx.restore()}}
function renderWorld(time){ctx.clearRect(0,0,w,h);ctx.imageSmoothingEnabled=false;const bob=Math.round(Math.sin(state.player.bob)*1.5);drawSkyGround(bob,time);const fov=Math.PI/2.0;drawPerimeterFence(fov,bob);drawVillageLandmarks(fov,bob,time);const cols=w;const zbuf=new Float32Array(cols);for(let c=0;c<cols;c++){const cam=(c/(cols-1)-.5)*2;const ra=state.player.a+cam*fov/2;const hit=castRay(ra);const corrected=hit.dist*Math.cos(ra-state.player.a);zbuf[c]=corrected;drawWallColumn(c,1,hit,bob,ra,time,corrected)}drawWorldSprites(zbuf,fov,bob,time);drawSnow(time);drawBreath(time);drawPSXPost(time)}
function drawSkyGround(bob,time){const dusk=clamp((state.minutes-850)/230,0,.55),horizon=Math.floor(h*.52+bob);ctx.fillStyle=`rgb(${Math.floor(88-42*dusk)},${Math.floor(101-46*dusk)},${Math.floor(99-48*dusk)})`;ctx.fillRect(0,0,w,horizon);for(let y=0;y<horizon;y+=3){const haze=clamp(y/Math.max(1,horizon),0,1);ctx.fillStyle=`rgba(184,191,184,${.02+haze*.04})`;ctx.fillRect(0,y,w,1)}drawDistantTreeline(horizon,time);drawFloor(horizon,time)}
function drawDistantTreeline(horizon,time){ctx.fillStyle='rgba(48,54,49,.42)';for(let x=0;x<w;x+=4){const n=((x*17+Math.floor(state.player.a*43))%19);const th=5+(n%9);ctx.fillRect(x,horizon-th,2,th)}ctx.fillStyle='rgba(86,91,85,.24)';ctx.fillRect(0,horizon-2,w,2)}
function groundKind(x,y){if(x<.95||y<.95||x>15.05||y>15.05)return'deep';if(inRects(x,y,ROAD_RECTS))return'road';if(inRects(x,y,PATH_RECTS))return'path';return'snow'}
function groundNoise(x,y){let n=(Math.floor(x*19)*73856093)^(Math.floor(y*19)*19349663);n=(n^(n>>>13))*1274126177;return((n>>>8)&255)/255}
function floorColor(kind,x,y,dist){const n=groundNoise(x,y);let c;if(kind==='road'){c=n>.86?[96,96,89]:n<.14?[59,61,57]:[73,75,70];const vx=Math.abs(((x*1.7)%1)-.5),vy=Math.abs(((y*1.7)%1)-.5);if(vx<.055||vy<.055)c=[57,60,57]}else if(kind==='path'){c=n>.78?[131,132,124]:[111,113,107]}else if(kind==='deep'){c=n>.65?[157,161,157]:[143,148,145]}else{c=n>.8?[169,169,158]:n<.12?[139,142,136]:[154,156,148]}const fog=clamp((dist-24)/42,0,.06),fogC=[143,151,145];return c.map((v,i)=>Math.round(v*(1-fog)+fogC[i]*fog))}
function drawFloor(horizon,time){ctx.fillStyle='#989a91';ctx.fillRect(0,horizon,w,h-horizon);const fov=Math.PI/2.0,la=state.player.a-fov/2,ra=state.player.a+fov/2,lx=Math.cos(la),ly=Math.sin(la),rx=Math.cos(ra),ry=Math.sin(ra);for(let y=horizon+1;y<h;y++){const p=y-horizon+.5,rowDist=(h*.39)/p,stepX=rowDist*(rx-lx)/w,stepY=rowDist*(ry-ly)/w;let wx=state.player.x+rowDist*lx,wy=state.player.y+rowDist*ly;for(let x=0;x<w;x+=2){const kind=groundKind(wx,wy),c=floorColor(kind,wx,wy,rowDist);ctx.fillStyle=`rgb(${c[0]},${c[1]},${c[2]})`;ctx.fillRect(x,y,2,1);wx+=stepX*2;wy+=stepY*2}}const edgeY=Math.floor(h*.77);ctx.fillStyle='rgba(41,42,38,.12)';ctx.fillRect(0,edgeY,w,1)}
function castRay(a){const ox=state.player.x,oy=state.player.y,dx=Math.cos(a),dy=Math.sin(a);let mx=Math.floor(ox),my=Math.floor(oy);const ddx=Math.abs(1/(dx||.0001)),ddy=Math.abs(1/(dy||.0001));let sx,sy,sdx,sdy;if(dx<0){sx=-1;sdx=(ox-mx)*ddx}else{sx=1;sdx=(mx+1-ox)*ddx}if(dy<0){sy=-1;sdy=(oy-my)*ddy}else{sy=1;sdy=(my+1-oy)*ddy}let side=0,wall=0;for(let i=0;i<48;i++){if(sdx<sdy){sdx+=ddx;mx+=sx;side=0}else{sdy+=ddy;my+=sy;side=1}wall=(MAP[my]&&MAP[my][mx])||1;if(wall)break}let dist=side===0?(mx-ox+(1-sx)/2)/(dx||.0001):(my-oy+(1-sy)/2)/(dy||.0001);dist=Math.max(.05,Math.abs(dist));let wx=side===0?oy+dist*dy:ox+dist*dx;wx-=Math.floor(wx);return{dist,wall,side,wx,mx,my,dx,dy}}
function shadeRGB(rgbv,k){return rgbv.map(v=>clamp(Math.round(v*k),0,255))}
function rgb(c){return`rgb(${c[0]},${c[1]},${c[2]})`}
function facadeCoord(hit){return hit.side===0?hit.my+hit.wx:hit.mx+hit.wx}
function drawMaterialColumn(x,top,wh,hit,b,shade,time){const fc=facadeCoord(hit),u=((fc%1)+1)%1;let base=shadeRGB(b.base,shade);if(b.material==='corrugated'){const ridge=Math.floor(u*16)%2;base=shadeRGB(base,ridge?1.05:.83)}else if(b.material==='brick'){const course=Math.floor((top+wh*.45)/5);if(Math.floor(u*8+(course%2)*.5)%4===0)base=shadeRGB(base,.74)}else if(b.material==='timber'){if(Math.floor(u*12)%3===0)base=shadeRGB(base,.72)}else if(b.material==='panel'){if(u<.035||u>.965)base=shadeRGB(base,.76)}else if(b.material==='stucco'){const n=((hit.mx*17+hit.my*31+Math.floor(u*20)*7)%13)-6;base=base.map(v=>clamp(v+n,0,255))}ctx.fillStyle=rgb(base);ctx.fillRect(x,top,1,wh);if(b.material==='brick'||b.material==='panel'||b.material==='concrete'){const step=b.material==='brick'?6:Math.max(10,Math.floor(wh/(b.floors*3)));ctx.fillStyle=`rgba(35,34,31,${b.material==='brick'?.28:.15})`;for(let yy=top+step;yy<top+wh;yy+=step)ctx.fillRect(x,Math.floor(yy),1,1)}if(b.material==='corrugated'&&Math.floor(u*24)%4===0){ctx.fillStyle='rgba(230,225,203,.12)';ctx.fillRect(x,top,1,wh)}}
function drawFacadeFeatures(x,top,wh,hit,b,shade){const fc=facadeCoord(hit),u=((fc%1)+1)%1,cell=`${hit.mx},${hit.my}`,door=b.doorCells.includes(cell);const floorSpan=.69/b.floors;for(let f=0;f<b.floors;f++){const wy=top+wh*(.15+f*floorSpan),hh=Math.max(2,wh*(.12/Math.max(1,b.floors)));let inWindow=false;if(b.id==='warehouse'||b.id==='workshop')inWindow=u>.12&&u<.86;else if(b.id==='chapel')inWindow=u>.33&&u<.67;else inWindow=(u>.17&&u<.39)||(u>.61&&u<.83);if(inWindow&&!door){const wc=shadeRGB(b.window,clamp(shade*1.15,.4,1.1));ctx.fillStyle=rgb(wc);ctx.fillRect(x,Math.floor(wy),1,Math.ceil(hh));if((Math.floor(u*40)+f)%7===0){ctx.fillStyle='rgba(199,190,151,.55)';ctx.fillRect(x,Math.floor(wy+hh*.2),1,Math.max(1,Math.floor(hh*.32)))}}}if(door&&u>.23&&u<.77){ctx.fillStyle=rgb(shadeRGB(b.trim,shade*.72));ctx.fillRect(x,Math.floor(top+wh*.58),1,Math.ceil(wh*.42));if(u>.70&&u<.74){ctx.fillStyle='rgba(194,174,112,.8)';ctx.fillRect(x,Math.floor(top+wh*.78),1,1)}}if(b.id==='apartments'&&!door&&u>.05&&u<.95&&Math.floor(u*10)%5===0){ctx.fillStyle='rgba(37,36,33,.34)';ctx.fillRect(x,Math.floor(top+wh*.43),1,Math.max(1,Math.floor(wh*.04)))}if(b.id==='clinic'&&!door&&u>.45&&u<.55){ctx.fillStyle='rgba(126,48,42,.75)';ctx.fillRect(x,Math.floor(top+wh*.27),1,Math.max(2,Math.floor(wh*.12)))}}
function drawBoundaryColumn(x,hit,bob,corrected,time){return}
function drawWallColumn(x,cw,hit,bob,a,time,corrected){const b=buildingAtCell(hit.mx,hit.my,hit.wall);if(b.id==='edge'){drawBoundaryColumn(x,hit,bob,corrected,time);return}const horizon=h*.52+bob,baseH=h/Math.max(.08,corrected)*.78,bottom=horizon+baseH*.5;let wh=Math.min(h*2.3,baseH*b.height),top=bottom-wh;const wobble=Math.sin(time*.006+x*.73+hit.mx*2.1+hit.my)*clamp(1.2-corrected*.08,.12,.95);top=Math.round(top+wobble);wh=Math.round(wh);const sideShade=hit.side?.77:1,distShade=clamp(1-corrected/13,.28,1),shade=sideShade*distShade;drawMaterialColumn(x,top,wh,hit,b,shade,time);drawFacadeFeatures(x,top,wh,hit,b,shade);const roofH=Math.max(1,Math.round(wh*(b.roof==='eave'?.045:.025)));ctx.fillStyle=rgb(shadeRGB(b.roof==='metal'?[58,57,52]:b.roof==='eave'?[45,38,31]:[207,207,193],clamp(shade+.08,.35,1)));ctx.fillRect(x,top,1,roofH);if(b.roof==='industrial'&&Math.floor(facadeCoord(hit)*4)%3===0){ctx.fillStyle='rgba(25,28,27,.55)';ctx.fillRect(x,top+roofH,1,Math.max(1,Math.round(wh*.05)))}const fog=clamp((corrected-24)/42,0,.06);if(fog>0){ctx.fillStyle=`rgba(143,151,145,${Math.floor(fog*8)/8})`;ctx.fillRect(x,top,1,wh)}}
function projectSprite(px,py,fov,bob){const dx=px-state.player.x,dy=py-state.player.y,dist=Math.hypot(dx,dy);let ang=Math.atan2(dy,dx)-state.player.a;ang=Math.atan2(Math.sin(ang),Math.cos(ang));if(Math.abs(ang)>fov*.72)return null;const sx=Math.round(w/2+(ang/(fov/2))*w/2);return{sx,dist,y:Math.floor(h*.52+bob)}}
function drawWorldSprites(zbuf,fov,bob,time){const sprites=[];const living=alive();NPC_POINTS.forEach((p,i)=>sprites.push({type:'npc',x:p.x,y:p.y,name:living[(i*5+state.day)%Math.max(1,living.length)]?.name||'Resident',idx:i}));PROPS.forEach((p,i)=>sprites.push({...p,idx:i}));sprites.sort((a,b)=>Math.hypot(b.x-state.player.x,b.y-state.player.y)-Math.hypot(a.x-state.player.x,a.y-state.player.y));for(const s of sprites){const p=projectSprite(s.x,s.y,fov,bob);if(!p||p.dist>30)continue;const col=clamp(Math.floor(p.sx),0,zbuf.length-1);if(zbuf[col]&&p.dist>zbuf[col]+.12)continue;if(s.type==='npc')drawNpcSprite(s,p,time);else drawPropSprite(s,p,time)}drawNearbySiteName(fov,bob)}
function drawNearbySiteName(fov,bob){let best=null,bd=3.6;for(const s of SITES){const p=projectSprite(s.x,s.y,fov,bob);if(p&&p.dist<bd){best={s,p};bd=p.dist}}if(!best)return;const {s,p}=best;ctx.fillStyle='rgba(12,13,11,.72)';const tw=Math.min(112,Math.max(50,s.name.length*5+12));ctx.fillRect(Math.round(p.sx-tw/2),Math.round(h*.78),tw,12);ctx.fillStyle='#ddd9c9';ctx.font='7px monospace';ctx.textAlign='center';ctx.fillText(s.name.toUpperCase(),p.sx,Math.round(h*.78+8))}
function drawNpcSprite(s,p,time){const H=clamp(120/p.dist,13,72),step=Math.sin(time*.007+s.idx)*H*.025;ctx.save();ctx.translate(Math.round(p.sx+step),Math.round(p.y+H*.34));ctx.globalAlpha=clamp(1-(p.dist-5)/8,.35,1);const coat=s.idx%3===0?'#4a514b':s.idx%3===1?'#4e4741':'#3f4847';ctx.fillStyle='#c0aa91';ctx.fillRect(-Math.round(H*.055),-Math.round(H*.69),Math.max(2,Math.round(H*.11)),Math.max(2,Math.round(H*.10)));ctx.fillStyle='#30332f';ctx.fillRect(-Math.round(H*.09),-Math.round(H*.76),Math.max(3,Math.round(H*.18)),Math.max(2,Math.round(H*.07)));ctx.fillStyle=coat;ctx.beginPath();ctx.moveTo(-H*.15,-H*.57);ctx.lineTo(H*.15,-H*.57);ctx.lineTo(H*.21,-H*.08);ctx.lineTo(H*.12,0);ctx.lineTo(-H*.13,0);ctx.lineTo(-H*.21,-H*.08);ctx.closePath();ctx.fill();ctx.fillStyle='#292b28';ctx.fillRect(-Math.round(H*.12),0,Math.max(2,Math.round(H*.08)),Math.round(H*.25));ctx.fillRect(Math.round(H*.04),0,Math.max(2,Math.round(H*.08)),Math.round(H*.25));if(p.dist<2.1){ctx.fillStyle='rgba(10,11,9,.8)';ctx.fillRect(-Math.round(H*.46),-Math.round(H*.95),Math.round(H*.92),Math.max(7,Math.round(H*.14)));ctx.fillStyle='#d8d5c7';ctx.font=`${Math.max(6,Math.round(H*.055))}px monospace`;ctx.textAlign='center';ctx.fillText(s.name,0,-Math.round(H*.85))}ctx.restore()}
function drawPropSprite(s,p,time){const H=clamp((s.type==='car'?175:110)/p.dist,s.type==='car'?13:8,s.type==='car'?90:64);ctx.save();ctx.translate(p.sx,p.y);ctx.globalAlpha=clamp(1-(p.dist-7)/6,.35,1);if(s.type==='lamp'){ctx.fillStyle='#2f342f';ctx.fillRect(-1,-H,2,H);ctx.fillStyle='#454a42';ctx.fillRect(-4,-H,8,4);ctx.fillStyle='rgba(189,172,117,.62)';ctx.fillRect(-2,-H+1,4,2)}else if(s.type==='tree'){ctx.strokeStyle='#3c3932';ctx.lineWidth=Math.max(1,H*.04);ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,-H);ctx.moveTo(0,-H*.55);ctx.lineTo(-H*.28,-H*.82);ctx.moveTo(0,-H*.68);ctx.lineTo(H*.25,-H*.92);ctx.moveTo(-H*.08,-H*.72);ctx.lineTo(-H*.18,-H);ctx.stroke()}else if(s.type==='barrels'){ctx.fillStyle='#5a5545';ctx.fillRect(-H*.26,-H*.28,H*.22,H*.28);ctx.fillRect(H*.02,-H*.31,H*.22,H*.31);ctx.fillStyle='#282b27';ctx.fillRect(-H*.26,-H*.22,H*.22,1);ctx.fillRect(H*.02,-H*.24,H*.22,1)}else if(s.type==='car'){ctx.fillStyle='#4c5550';ctx.fillRect(-H*.48,-H*.23,H*.96,H*.20);ctx.fillStyle='#303633';ctx.fillRect(-H*.25,-H*.40,H*.48,H*.18);ctx.fillStyle='#171a18';ctx.fillRect(-H*.39,-H*.07,H*.16,H*.10);ctx.fillRect(H*.23,-H*.07,H*.16,H*.10);ctx.fillStyle='#758078';ctx.fillRect(-H*.17,-H*.35,H*.13,H*.10);ctx.fillRect(H*.04,-H*.35,H*.13,H*.10)}else if(s.type==='fence'){ctx.fillStyle='#4a4a42';for(let i=-2;i<=2;i++)ctx.fillRect(i*H*.12,-H*.42,1,H*.42);ctx.fillRect(-H*.30,-H*.32,H*.60,1);ctx.fillRect(-H*.30,-H*.16,H*.60,1)}else if(s.type==='roadsign'){ctx.fillStyle='#373a34';ctx.fillRect(-1,-H*.68,2,H*.68);ctx.fillStyle='#6d725f';ctx.fillRect(-H*.3,-H*.7,H*.6,H*.18);ctx.fillStyle='#d5d1bd';ctx.font=`${Math.max(5,Math.round(H*.07))}px monospace`;ctx.textAlign='center';ctx.fillText(s.label||'',0,-H*.57)}ctx.restore()}
function drawSnow(time){ctx.fillStyle='rgba(242,242,228,.88)';for(let i=0;i<72;i++){const speed=7+(i%6)*3;const x=Math.floor((i*53+time*.012*(i%3+1))%(w+12)-6);const y=Math.floor((i*31+time*.009*speed)%(h+12)-6);ctx.fillRect(x,y,i%11===0?2:1,i%13===0?2:1)}}
function drawBreath(time){const ph=Math.sin(time*.0018);if(ph>-.25){const a=(ph+.25)/1.25*.08;ctx.fillStyle=`rgba(225,229,220,${a})`;ctx.fillRect(Math.floor(w*.43),Math.floor(h*.76),Math.floor(w*.14),2);ctx.fillRect(Math.floor(w*.46),Math.floor(h*.74),Math.floor(w*.08),1)}}
function drawPSXPost(time){const bayer=[[0,8,2,10],[12,4,14,6],[3,11,1,9],[15,7,13,5]];ctx.save();ctx.globalAlpha=.055;ctx.fillStyle='#10120f';for(let y=0;y<h;y+=2)for(let x=0;x<w;x+=2)if(bayer[(y>>1)&3][(x>>1)&3]>9)ctx.fillRect(x,y,1,1);ctx.restore();if((Math.floor(time/90)%17)===0){ctx.fillStyle='rgba(220,222,205,.025)';ctx.fillRect(0,Math.floor((time*.021)%h),w,1)}}
function renderMiniMap(){if(!mapCtx)return;const cw=mapCanvas.width,ch=mapCanvas.height,ts=cw/MAP[0].length;mapCtx.imageSmoothingEnabled=false;mapCtx.fillStyle='#d0d1c5';mapCtx.fillRect(0,0,cw,ch);mapCtx.fillStyle='#555a55';for(const r of ROAD_RECTS)mapCtx.fillRect(r[0]*ts,r[2]*ts,(r[1]-r[0])*ts,(r[3]-r[2])*ts);mapCtx.fillStyle='#8e9188';for(const r of PATH_RECTS)mapCtx.fillRect(r[0]*ts,r[2]*ts,(r[1]-r[0])*ts,(r[3]-r[2])*ts);for(let y=0;y<MAP.length;y++)for(let x=0;x<MAP[y].length;x++){if(MAP[y][x]){const b=buildingAtCell(x,y,MAP[y][x]);if(b.id==='edge')continue;mapCtx.fillStyle=b.id==='clinic'?'#74847e':b.id==='apartments'?'#69655f':b.id==='workshop'?'#704b3c':b.id==='chapel'?'#514234':'#625b4d';mapCtx.fillRect(x*ts,y*ts,ts,ts)}}for(const s of SITES){mapCtx.fillStyle=s.accent;mapCtx.fillRect(Math.round(s.x*ts)-2,Math.round(s.y*ts)-2,4,4)}mapCtx.strokeStyle='#5d5b50';mapCtx.lineWidth=1;mapCtx.beginPath();mapCtx.moveTo(ts,ts);mapCtx.lineTo(15*ts,ts);mapCtx.lineTo(15*ts,15*ts);mapCtx.moveTo(ts,ts);mapCtx.lineTo(ts,15*ts);mapCtx.moveTo(ts,15*ts);mapCtx.lineTo(7*ts,15*ts);mapCtx.moveTo(9*ts,15*ts);mapCtx.lineTo(15*ts,15*ts);mapCtx.stroke();mapCtx.fillStyle='#343833';mapCtx.fillRect(7.0*ts,13.95*ts,1.0*ts,.32*ts);mapCtx.fillStyle='#231f1a';mapCtx.fillRect(Math.round(state.player.x*ts)-2,Math.round(state.player.y*ts)-2,4,4);mapCtx.strokeStyle='#231f1a';mapCtx.beginPath();mapCtx.moveTo(state.player.x*ts,state.player.y*ts);mapCtx.lineTo((state.player.x+Math.cos(state.player.a)*1.1)*ts,(state.player.y+Math.sin(state.player.a)*1.1)*ts);mapCtx.stroke()}
