function interact(){if(state.phase!=='field')return;if(nearSite)inspectSite(nearSite);else feedback('Nothing within reach','Move closer to a marked location and face it.','bad')}
function inspectSite(site){const actions=[];if(site.kind==='hall'){actions.push({label:'Open population ledger',detail:'Begin evening triage',run:openLedger});actions.push({label:'Review the office',detail:'15 min · records',run:()=>{addTime(15,'Town Hall: reviewed conflicting residency records.');assessResidents(1,0,'Town Hall',false);feedback('Records compared','One resident record is now more reliable.','good')}})}if(site.kind==='loot'){actions.push({label:'Search rooms and containers',detail:'45 min · food / heat / scrap',run:()=>scavenge(site,45,'search')});actions.push({label:'Dismantle usable material',detail:'90 min · heat / scrap',run:()=>scavenge(site,90,'dismantle')})}if(site.kind==='clinic'){actions.push({label:'Search pharmacy cabinets',detail:'60 min · medicine',run:()=>scavenge(site,60,'clinic')});actions.push({label:'Review treatment cards',detail:'35 min · assess 3 residents',run:()=>assessResidents(3,35,site.name)})}if(site.kind==='people'){actions.push({label:'Interview a household',detail:'35 min · assess 1 resident',run:()=>assessResidents(1,35,site.name)});actions.push({label:'Inspect rooms and stove',detail:'50 min · supplies / intelligence',run:()=>scavenge(site,50,'people')})}showModal(`<div class="eyebrow">${escapeHtml(site.kind)} · ${fmtTime(state.minutes)}</div><h2>${escapeHtml(site.name)}</h2><p>${escapeHtml(site.desc)}</p><div class="action-list">${actions.map((a,i)=>`<button data-act="${i}"><span>${escapeHtml(a.label)}</span><small>${escapeHtml(a.detail)}</small></button>`).join('')}</div><button class="ghost wide modal-close">Leave</button>`);actions.forEach((a,i)=>$(`[data-act="${i}"]`).onclick=()=>{hideModal();a.run()});$('.modal-close').onclick=hideModal}
function scavenge(site,min,type){const uses=state.siteUses[site.id]||0;state.siteUses[site.id]=uses+1;const dep=Math.max(.2,1-uses*.23);let food=0,heat=0,med=0,scrap=0;if(type==='search'){food=+(randInt(1,5)*dep).toFixed(1);heat=+(randInt(0,3)*dep).toFixed(1);scrap=randInt(0,2)}if(type==='dismantle'){heat=+(randInt(2,6)*dep).toFixed(1);scrap=randInt(2,5)}if(type==='clinic'){med=+(randInt(1,4)*dep).toFixed(1);food=rand()<.25?1:0}if(type==='people'){food=+(randInt(0,3)*dep).toFixed(1);heat=+(randInt(0,2)*dep).toFixed(1);if(rand()<.38)assessResidents(1,0,site.name,false)}state.stock.food+=food;state.stock.heat+=heat;state.stock.med+=med;state.stock.scrap+=scrap;addTime(min,`${site.name}: recovered ${food} nutrition, ${heat} heat, ${med} medicine, ${scrap} scrap.`);screenFlash('loot');feedback('Supplies recovered',`+${food} food · +${heat} heat · +${med} medicine · +${scrap} scrap`,'good');save(false);advanceTutorialByAction('scavenge')}
function assessResidents(count,min,source,log=true){const unknown=alive().filter(p=>!p.assessed),picked=[];for(let i=0;i<count&&unknown.length;i++){const ix=Math.floor(rand()*unknown.length);const p=unknown.splice(ix,1)[0];p.assessed=true;picked.push(p)}if(min)addTime(min,`${source}: ${picked.map(p=>p.name).join(', ')||'no new residents'} assessed.`);else if(log&&picked.length)logField(`${source}: ${picked.map(p=>p.name).join(', ')} assessed.`);if(picked.length){feedback('Information improved',picked.map(p=>p.name).join(' · '),'good');advanceTutorialByAction('assess')}save(false)}
function screenFlash(type){const fx=$('#screenFx');fx.className=`screen-fx ${type}`;clearTimeout(flashTimer);flashTimer=setTimeout(()=>fx.className='screen-fx',240)}
function feedback(title,sub,type=''){const box=document.createElement('div');box.className=`feedback-item ${type}`;box.innerHTML=`<b>${escapeHtml(title)}</b><small>${escapeHtml(sub)}</small>`;$('#feedbackFeed').prepend(box);setTimeout(()=>box.remove(),4000)}
function openLedger(){if(!state||state.phase==='ledger')return;hideModal();tutorial.active=false;$('#tutorialLayer').classList.add('hidden');clearMovementState();setPhase('ledger');applyPolicyDefaults();renderPolicies();renderLedger();save(false);advanceTutorialByAction('ledger')}
function closeLedger(){if(state.minutes>=1080){toast('Field operations have ended for the day');return}hideModal();tutorial.active=false;$('#tutorialLayer').classList.add('hidden');clearMovementState();setPhase('field');focusField()}
function renderPolicies(){if(!state)return;const gs=['children','essential','general','elderly'];$('#policyGrid').innerHTML=gs.map(g=>{const c=alive().filter(p=>p.cohort===g).length,pol=state.policies[g];return`<section class="policy-card" data-cohort="${g}"><header><span>${cohortLabel(g)}</span><small>${c} alive</small></header><label class="policy-line"><span>Food</span><input data-pol="food" type="range" min="0" max="125" step="25" value="${pol.food}"><output>${pol.food}%</output></label><label class="policy-line"><span>Heat</span><input data-pol="heat" type="range" min="0" max="125" step="25" value="${pol.heat}"><output>${pol.heat}%</output></label></section>`}).join('');$$('.policy-card input').forEach(inp=>inp.oninput=()=>{const card=inp.closest('.policy-card'),g=card.dataset.cohort,k=inp.dataset.pol;state.policies[g][k]=Number(inp.value);inp.nextElementSibling.textContent=`${inp.value}%`;applyPolicyDefaults();renderLedger()})}
function applyPolicyDefaults(){alive().forEach(p=>{const pol=state.policies[p.cohort];if(!p.ration.manualFood)p.ration.food=pol.food/100;if(!p.ration.manualHeat)p.ration.heat=pol.heat/100})}
function mutObj(p){return p.mutation?MUTATIONS.find(m=>m.name===p.mutation):null}
function requestedTotals(){return alive().reduce((a,p)=>{const m=mutObj(p);a.food+=p.ration.food*(m?.food||1);a.heat+=p.ration.heat*(m?.heat||1);a.med+=p.ration.med?1:0;return a},{food:0,heat:0,med:0})}
function condition(p){if(!p.alive)return`Dead · ${p.causeOfDeath}`;if(!p.assessed)return p.health<35?'Visibly poor':p.health<60?'Uncertain':'Appears stable';return p.health<25?'Critical':p.health<50?'Poor':p.health<75?'Strained':'Stable'}
function renderLedger(){if(!state)return;const q=($('#residentSearch').value||'').toLowerCase(),f=$('#residentFilter').value;const list=state.people.filter(p=>{if(q&&!(p.name+' '+p.job).toLowerCase().includes(q))return false;if(f==='critical'&&!(p.alive&&p.health<40))return false;if(f==='dissent'&&!(p.alive&&p.dissent>=60))return false;if(f==='known'&&!p.assessed)return false;if(f==='mutated'&&!p.mutation)return false;return true});$('#residentCards').innerHTML=list.map(p=>{const exact=p.assessed||!p.alive;return`<article class="resident-card ${!p.alive?'dead':''} ${p.dissent>70?'high-dissent':''}" data-id="${p.id}"><div class="resident-head"><div><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.job)} · age ${p.age}</small></div><span class="pill">${cohortLabel(p.cohort)}</span></div><div class="resident-meta"><span class="pill">${escapeHtml(condition(p))}</span>${p.assessed?'<span class="pill">ASSESSED</span>':''}${p.mutation?`<span class="pill">${escapeHtml(p.mutation)}</span>`:''}</div><div class="resident-state"><span>Health: ${exact?Math.round(p.health)+'%':'unknown'}</span><span>Dissent: ${exact?Math.round(p.dissent)+'%':p.dissent>55?'high?':'uncertain'}</span></div>${p.alive?`${allocRow(p,'food','Food')}${allocRow(p,'heat','Heat')}<label class="med-line"><input type="checkbox" data-med="${p.id}" ${p.ration.med?'checked':''}> Medicine tonight</label>`:''}</article>`}).join('');$$('[data-adjust]').forEach(b=>b.onclick=()=>adjust(Number(b.dataset.id),b.dataset.adjust,Number(b.dataset.delta)));$$('[data-med]').forEach(c=>c.onchange=()=>{const p=state.people.find(x=>x.id===Number(c.dataset.med));p.ration.med=c.checked;updateProjection()});updateProjection()}
function allocRow(p,k,label){return`<div class="alloc-row"><span>${label}</span><div class="ctrl"><button data-adjust="${k}" data-id="${p.id}" data-delta="-.25">−</button><b>${Math.round(p.ration[k]*100)}%</b><button data-adjust="${k}" data-id="${p.id}" data-delta=".25">+</button></div><small>${p.ration[k]===0?'none':p.ration[k]<.75?'low':p.ration[k]>=1?'full':'reduced'}</small></div>`}
function adjust(id,k,d){const p=state.people.find(x=>x.id===id);if(!p)return;p.ration[k]=clamp(p.ration[k]+d,0,1.5);p.ration[k==='food'?'manualFood':'manualHeat']=true;renderLedger()}
function updateProjection(){const t=requestedTotals(),over=t.food>state.stock.food+.001||t.heat>state.stock.heat+.001||t.med>state.stock.med+.001;const el=$('#projectionText');el.className=`projection ${over?'over':'ok'}`;el.innerHTML=`Requested <b>${t.food.toFixed(1)}</b> food · <b>${t.heat.toFixed(1)}</b> heat · <b>${t.med.toFixed(0)}</b> medicine — <strong>${over?'PLAN EXCEEDS STOCK':'PLAN FITS STOCK'}</strong>`;$('#sealLedgerBtn').disabled=over}
function fitPlan(){const a=alive();a.forEach(p=>{p.ration.food=.5;p.ration.heat=.5;p.ration.manualFood=true;p.ration.manualHeat=true});let t=requestedTotals();let guard=0;while(guard++<400){let changed=false;for(const p of [...a].sort((x,y)=>priority(y)-priority(x))){if(t.food+.25<=state.stock.food&&p.ration.food<1){p.ration.food+=.25;changed=true}if(t.heat+.25<=state.stock.heat&&p.ration.heat<1){p.ration.heat+=.25;changed=true}t=requestedTotals()}if(!changed)break}renderLedger();feedback('Plan fitted','A conservative allocation now fits available stock.','good')}
function priority(p){return(p.cohort==='children'?4:p.cohort==='essential'?3:p.cohort==='general'?2:1)+(100-p.health)/100}
function autoMedicine(){alive().forEach(p=>p.ration.med=false);[...alive()].sort((a,b)=>a.health-b.health).slice(0,Math.floor(state.stock.med)).forEach(p=>p.ration.med=true);renderLedger()}
