(() => {
  'use strict';
  const TUTORIAL_KEY = 'winterRegistryTutorial_v02';
  const LABELS = ['Resident','Role','Age','Condition','Dissent','Mutation','Food','Heat','Medicine'];
  const SITE_LIST = [
    {name:'Town Hall', x:4, y:5, kind:'hall', hint:'Ledger & policy'},
    {name:'Warehouse 3', x:2, y:2, kind:'loot', hint:'Food / salvage'},
    {name:'District Clinic', x:7, y:2, kind:'clinic', hint:'Medicine / records'},
    {name:'Eastern Block', x:7, y:6, kind:'people', hint:'Residents / intel'},
    {name:'Machine Workshop', x:2, y:6, kind:'loot', hint:'Heat / scrap'},
    {name:'Fuel Depot', x:5, y:1, kind:'loot', hint:'Heat / salvage'},
    {name:'Old Chapel', x:8, y:8, kind:'people', hint:'Residents / intel'},
    {name:'Ruined House', x:1, y:8, kind:'loot', hint:'Mixed supplies'},
    {name:'Abandoned Lada', x:5, y:8, kind:'loot', hint:'Scrap / fluids'}
  ];
  const steps = [
    {title:'You have one job: make tomorrow possible.',text:'Each day has three phases. In the field you spend time to gather supplies and learn who needs help. In the ledger you distribute those supplies. At night, the simulation resolves the consequences.',tip:'Nothing pauses because you are uncertain. Time and incomplete information are part of the game.',target:'#phaseRail',next:'Show me the field'},
    {title:'Watch the clock.',text:'Field operations run from 06:00 to 18:00. Travel and every action consume minutes. You cannot visit everything, so choose what the district needs most.',tip:'The top bar always shows the current day and time. Reaching 18:00 automatically ends field operations.',target:'.status-strip',next:'Understood'},
    {title:'Supplies become tonight’s decisions.',text:'Nutrition, heat and medicine are the resources you will distribute tonight. Scrap is retained for later systems. Your starting stock is deliberately insufficient for comfortable full rations.',tip:'Food and heat are measured in abstract ration units. One medicine unit can treat one resident for the night.',target:'.resource-section',next:'Choose a location'},
    {title:'Visit a location.',text:'Tap a building on the map, or use the location list. For your first trip, visit Warehouse 3, the Fuel Depot, the Clinic, or any other non–Town Hall site.',tip:'The list is not a teleport: selecting a location still charges its travel time.',target:'#siteDirectory',wait:'site',next:'Visit Warehouse 3'},
    {title:'Every action has a cost.',text:'A location gives you contextual actions. Their labels show how much time they consume and what kind of result to expect. Choose one action now.',tip:'Repeated scavenging depletes a site. Interviews and medical records can reveal exact resident information instead of estimates.',target:'#modalCard',wait:'action',next:'Search this location'},
    {title:'Return before the arithmetic begins.',text:'You can continue scavenging, or return to Town Hall whenever you think you have enough. For the tutorial, return now so you can learn the ledger.',tip:'Returning early is sometimes correct. Extra field time is worthless if you already have the information or resources you need.',target:'#returnBtn',wait:'ledger',next:'Return to Town Hall'},
    {title:'The ledger is the actual knife.',text:'Group sliders set default food and heat rations. Individual +/− controls override those defaults. Medicine can be assigned manually or triaged automatically. The requested total at the bottom must not exceed stock.',tip:'Residents you assessed in the field show reliable health. Everyone else is partly guesswork.',target:'#policyGrid',next:'Show me the safety check'},
    {title:'Balance the plan, then seal it.',text:'If the plan exceeds stock, the night cannot be resolved. “Fit Plan to Stock” gives you a survivable starting allocation; it is not necessarily an ethical or optimal one. Adjust it, then seal the ledger when you are ready.',tip:'After sealing, deaths, health changes, dissent and mutations are resolved. Morning begins with the consequences still in the population record.',target:'.ledger-foot',next:'Finish tutorial'}
  ];
  let tutorialActive=false, tutorialStep=0, lastPhase='';
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  function init(){ buildSiteDirectory(); bindUX(); observeUI(); labelResidentCells(); syncPhaseUI(); syncObjective(); syncProjectionState(); }
  function buildSiteDirectory(){ const host=$('#siteDirectory'); if(!host)return; host.innerHTML=SITE_LIST.map((s,i)=>`<button class="site-btn" type="button" data-site-index="${i}" data-kind="${s.kind}"><strong>${s.name}</strong><small>${s.hint}</small></button>`).join(''); host.addEventListener('click',e=>{const btn=e.target.closest('[data-site-index]');if(btn)visitSite(SITE_LIST[Number(btn.dataset.siteIndex)]);}); }
  function visitSite(site){ const canvas=$('#world'); if(!canvas||!$('#fieldView')?.classList.contains('active'))return; const rect=canvas.getBoundingClientRect(),originX=rect.width/2,originY=Math.max(74,rect.height*.12),px=originX+(site.x-site.y)*43,py=originY+(site.x+site.y)*21.5; const EventType=window.PointerEvent||window.MouseEvent; canvas.dispatchEvent(new EventType('pointerup',{bubbles:true,cancelable:true,clientX:rect.left+px,clientY:rect.top+py,pointerType:'touch'})); }
  function bindUX(){
    $('#helpBtn')?.addEventListener('click',()=>startTutorial(0,true));
    $('#newGameBtn')?.addEventListener('click',()=>setTimeout(()=>{syncPhaseUI();syncObjective();if(!localStorage.getItem(TUTORIAL_KEY))startTutorial(0,false);},80));
    $('#continueBtn')?.addEventListener('click',()=>setTimeout(()=>{syncPhaseUI();syncObjective();labelResidentCells();},80));
    $('#tutorialNext')?.addEventListener('click',nextTutorial); $('#tutorialSkip')?.addEventListener('click',finishTutorial); $('#fitRationsBtn')?.addEventListener('click',fitRationsToStock);
    $('#modalLayer')?.addEventListener('click',e=>{if(tutorialActive&&tutorialStep===4&&e.target.closest('.action-list button'))setTimeout(()=>setTutorialStep(5),120);},true);
    $('#returnBtn')?.addEventListener('click',()=>{if(tutorialActive&&tutorialStep===5)setTimeout(()=>setTutorialStep(6),100);});
    window.addEventListener('resize',()=>{if(tutorialActive)focusTutorialTarget();});
  }
  function observeUI(){ const modal=$('#modalLayer'); if(modal)new MutationObserver(()=>{if(tutorialActive&&tutorialStep===3&&!modal.classList.contains('hidden'))setTutorialStep(4);}).observe(modal,{attributes:true,attributeFilter:['class']}); const ledger=$('#ledgerView'),field=$('#fieldView'); const phaseObserver=new MutationObserver(()=>{syncPhaseUI();syncObjective();labelResidentCells();if(tutorialActive&&tutorialStep===5&&ledger?.classList.contains('active'))setTutorialStep(6);}); if(ledger)phaseObserver.observe(ledger,{attributes:true,attributeFilter:['class']}); if(field)phaseObserver.observe(field,{attributes:true,attributeFilter:['class']}); const rows=$('#residentRows'); if(rows)new MutationObserver(labelResidentCells).observe(rows,{childList:true,subtree:true}); const projection=$('#projectionText'); if(projection)new MutationObserver(syncProjectionState).observe(projection,{childList:true,subtree:true,characterData:true}); ['#timeLabel','#dayLabel','#foodStock','#heatStock','#medStock'].forEach(sel=>{const el=$(sel);if(el)new MutationObserver(syncObjective).observe(el,{childList:true,subtree:true,characterData:true});}); }
  function syncPhaseUI(){ const fieldActive=$('#fieldView')?.classList.contains('active'),ledgerActive=$('#ledgerView')?.classList.contains('active'),phase=fieldActive?'field':ledgerActive?'ledger':'night'; if(phase===lastPhase)return;lastPhase=phase; $$('#phaseRail > div').forEach(el=>{const p=el.dataset.phase;el.classList.toggle('active',p===phase);el.classList.toggle('done',(phase==='ledger'&&p==='field')||(phase==='night'&&p!=='night'));}); }
  function syncObjective(){ const title=$('#objectiveTitle'),body=$('#objectiveBody'); if(!title||!body)return; if($('#ledgerView')?.classList.contains('active')){title.textContent='Balance tonight’s ledger';body.textContent='Keep requested food, heat and medicine within stock, then seal the ledger.';return;} const time=($('#timeLabel')?.textContent||'06:00').split(':').map(Number),mins=(time[0]||0)*60+(time[1]||0),food=Number($('#foodStock')?.textContent||0),heat=Number($('#heatStock')?.textContent||0),med=Number($('#medStock')?.textContent||0); if(mins>=1020){title.textContent='Dusk is close — return to Town Hall';body.textContent='At 18:00 field operations end automatically. Spend only what time remains.';}else if(food<20||heat<18){title.textContent='Build a survivable reserve';body.textContent=`Current stock: ${food.toFixed(1)} nutrition · ${heat.toFixed(1)} heat · ${med.toFixed(1)} medicine.`;}else{title.textContent='Information may be worth more than another ration';body.textContent='Consider interviewing households or reviewing clinic records before returning.';} }
  function labelResidentCells(){ $$('#residentRows tr').forEach(row=>[...row.children].forEach((cell,i)=>cell.dataset.label=LABELS[i]||'Record')); }
  function syncProjectionState(){ const el=$('#projectionText');if(!el)return;const bad=/STOCK EXCEEDED/i.test(el.textContent||'');el.classList.toggle('stock-bad',bad);el.classList.toggle('stock-ok',!bad&&/Requested:/i.test(el.textContent||'')); }
  function fitRationsToStock(){ const cards=Object.fromEntries($$('.policy-card').map(card=>[card.dataset.cohort,card]));if(!Object.keys(cards).length)return; const set=(cohort,key,value)=>{const input=cards[cohort]?.querySelector(`[data-pol="${key}"]`);if(!input)return;input.value=String(value);input.dispatchEvent(new Event('input',{bubbles:true}));}; [['children',100,100],['essential',100,100],['general',75,75],['elderly',50,75]].forEach(([c,f,h])=>{set(c,'food',f);set(c,'heat',h);}); $('#autoMedicineBtn')?.click(); const order=[['elderly','food'],['general','food'],['elderly','heat'],['general','heat'],['essential','heat'],['children','heat'],['essential','food'],['children','food']]; let guard=0; while($('#sealLedgerBtn')?.disabled&&guard<40){const pair=order[guard%order.length],input=cards[pair[0]]?.querySelector(`[data-pol="${pair[1]}"]`);if(input&&Number(input.value)>0){input.value=String(Math.max(0,Number(input.value)-25));input.dispatchEvent(new Event('input',{bubbles:true}));}guard++;} uxToast($('#sealLedgerBtn')?.disabled?'Stock is critically low. Reduce individual allocations.':'Conservative plan fitted to current stock. Review before sealing.');syncProjectionState(); }
  function uxToast(message){const toast=$('#toast');if(!toast)return;toast.textContent=message;toast.classList.remove('hidden');clearTimeout(uxToast.timer);uxToast.timer=setTimeout(()=>toast.classList.add('hidden'),3200);}
  function startTutorial(at=0,replay=false){tutorialActive=true;tutorialStep=Math.max(0,Math.min(steps.length-1,at));$('#tutorialLayer')?.classList.remove('hidden');if(replay)uxToast('Orientation tutorial restarted');renderTutorial();}
  function setTutorialStep(n){if(!tutorialActive)return;tutorialStep=Math.max(0,Math.min(steps.length-1,n));renderTutorial();}
  function nextTutorial(){if(!tutorialActive)return;const step=steps[tutorialStep];if(step.wait==='site'){visitSite(SITE_LIST[1]);return;}if(step.wait==='action'){document.querySelector('.action-list button')?.click();return;}if(step.wait==='ledger'){$('#returnBtn')?.click();return;}if(tutorialStep>=steps.length-1)finishTutorial();else setTutorialStep(tutorialStep+1);}
  function finishTutorial(){tutorialActive=false;localStorage.setItem(TUTORIAL_KEY,'complete');$('#tutorialLayer')?.classList.add('hidden');$('#tutorialFocus')?.classList.add('hidden');uxToast('Orientation complete. Help (?) can replay it at any time.');}
  function renderTutorial(){const step=steps[tutorialStep];if(!step)return;$('#tutorialStepLabel').textContent=`${tutorialStep+1} / ${steps.length}`;$('#tutorialProgressBar').style.width=`${((tutorialStep+1)/steps.length)*100}%`;$('#tutorialTitle').textContent=step.title;$('#tutorialText').textContent=step.text;$('#tutorialTip').textContent=step.tip||'';const next=$('#tutorialNext');next.textContent=step.next||'Continue';next.disabled=false;$('#tutorialLayer').classList.toggle('soft',!!step.target);requestAnimationFrame(focusTutorialTarget);}
  function focusTutorialTarget(){const focus=$('#tutorialFocus');if(!tutorialActive||!focus)return;const step=steps[tutorialStep],target=step?.target?$(step.target):null;if(!target||target.offsetParent===null){focus.classList.add('hidden');return;}const r=target.getBoundingClientRect(),pad=6;focus.style.left=`${Math.max(3,r.left-pad)}px`;focus.style.top=`${Math.max(3,r.top-pad)}px`;focus.style.width=`${Math.min(window.innerWidth-r.left+pad-3,r.width+pad*2)}px`;focus.style.height=`${Math.min(window.innerHeight-r.top+pad-3,r.height+pad*2)}px`;focus.classList.remove('hidden');}
  document.addEventListener('DOMContentLoaded',init);
})();
