(() => {
'use strict';

const SAVE_KEY='winterRegistrySave_v03';
const TUTORIAL_KEY='winterRegistryTutorial_v03';
const GAME_DAYS=14;
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)); const pad=n=>String(n).padStart(2,'0');
const fmtTime=m=>`${pad(Math.floor(m/60)%24)}:${pad(Math.round(m)%60)}`;

const NAMES=['Aleksandr Petrov','Irina Petrova','Mikhail Antonov','Svetlana Orlova','Yuri Morozov','Nadezhda Volkova','Viktor Sokolov','Elena Sokolova','Pavel Lebedev','Galina Lebedeva','Boris Kuznetsov','Tatiana Kuznetsova','Nikolai Fedorov','Anya Fedorova','Sergei Popov','Lidia Popova','Grigori Smirnov','Vera Smirnova','Oleg Makarov','Raisa Makarova','Lev Zakharov','Zoya Zakharova','Andrei Pavlov','Marina Pavlova','Konstantin Belov','Larisa Belova','Dmitri Voronin','Katya Voronina','Roman Gusev','Maya Guseva'];
const JOBS=['Carpenter','Nurse','Heating engineer','Teacher','Warehouse labourer','Retired machinist','Mechanic','Clerk','Doctor','Agricultural worker','Electrician','Cook','Watchman','Seamstress','Sanitation worker','Driver','Midwife','Boiler operator','Radio technician','Archivist','Mason','Student','Rail worker','Chemist'];
const ESSENTIAL=new Set(['Nurse','Heating engineer','Warehouse labourer','Mechanic','Doctor','Agricultural worker','Electrician','Cook','Boiler operator','Chemist']);
const MUTATIONS=[
{name:'Dermal Keratinisation',desc:'Skin hardens into plates. Cold resistance improves; manual dexterity collapses.',food:1,heat:.45,aura:2},
{name:'Hypermetabolic Growth',desc:'Muscle and connective tissue thicken rapidly. Labour capacity rises; caloric demand becomes extreme.',food:1.75,heat:.8,aura:2},
{name:'Fused Mandible',desc:'The jaw calcifies shut. Food requirements fall, but ordinary treatment becomes difficult.',food:.35,heat:1,aura:4},
{name:'Auditory Mimicry',desc:'The resident repeats conversations they could not have heard. Others avoid them.',food:1,heat:1,aura:6}
];
const MAP=[
'1111111111111111','1000000000000001','1033300002222001','1030300002022001','1033300002222001','1000000000000001','1001110003330001','1001010003030001','1001110003330001','1000000000000001','1022200444000001','1020200404000001','1022200444003301','1000000000003031','1000000000003301','1111111111111111'].map(r=>r.split('').map(Number));
const SITES=[
{id:'hall',name:'Town Hall',x:3.5,y:3.5,kind:'hall',desc:'The municipal offices. The stove still works. The files do not agree with one another.',accent:'#b9ad83'},
{id:'warehouse',name:'Warehouse 3',x:10.5,y:3.5,kind:'loot',desc:'Corrugated storage, padlock broken, inventory board blank.',accent:'#9a8468'},
{id:'clinic',name:'District Clinic',x:4.5,y:7.5,kind:'clinic',desc:'A concrete clinic with cracked windows and treatment cards stacked by the stove.',accent:'#94aba4'},
{id:'apartments',name:'Eastern Block',x:10.5,y:7.5,kind:'people',desc:'Six households share a stairwell, one stove and several mutually incompatible stories.',accent:'#9a8c80'},
{id:'workshop',name:'Machine Workshop',x:3.5,y:11.5,kind:'loot',desc:'Frozen tools, a stripped generator and enough sharp metal to make mistakes permanent.',accent:'#9d8064'},
{id:'fuel',name:'Fuel Depot',x:8.5,y:11.5,kind:'loot',desc:'Coal dust and diesel. The fence was opened from the inside.',accent:'#a79569'},
{id:'chapel',name:'Old Chapel',x:13.5,y:13.5,kind:'people',desc:'Candles burn despite the ration order. Snow blows through the roof.',accent:'#a79e7c'}
];
const NPC_POINTS=[{x:6.5,y:4.8},{x:12.1,y:6.0},{x:6.2,y:10.3},{x:11.7,y:12.8},{x:8.2,y:8.4}];

let state=null,rng=Math.random;
let canvas,ctx,mapCanvas,mapCtx,dpr=1,w=1,h=1;
let keys={},touch={forward:false,back:false,left:false,right:false,lookL:false,lookR:false};
let lastT=0,dragging=false,lastPointerX=0,animId=0;
let deferredInstallPrompt=null,nearSite=null;
let tutorial={active:false,step:0};
let flashTimer=0;

function hashSeed(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function mulberry32(a){return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function rand(){return rng()} function randInt(a,b){return Math.floor(rand()*(b-a+1))+a} function choice(a){return a[Math.floor(rand()*a.length)]}
function makeSeed(){const c='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='WINTER-';for(let i=0;i<6;i++)s+=c[Math.floor(Math.random()*c.length)];return s}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

function makeState(){const seed=makeSeed();rng=mulberry32(hashSeed(seed));const people=NAMES.map((name,i)=>{const age=i<4?randInt(8,16):(i>25?randInt(63,79):randInt(19,62));const job=i<4?'Student':choice(JOBS);return{id:i+1,name,age,job,alive:true,cohort:age<18?'children':age>=65?'elderly':ESSENTIAL.has(job)?'essential':'general',health:randInt(62,96),hunger:randInt(45,78),warmth:randInt(48,82),rad:+(rand()*1.7).toFixed(2),dissent:randInt(5,28),assessed:i<2,mutation:null,ration:{food:1,heat:1,med:false},district:i%3===0?'Eastern Block':i%3===1?'Central District':'Industrial Fringe',history:[],causeOfDeath:null,dayOfDeath:null}});return{version:3,seed,day:1,minutes:360,phase:'field',stock:{food:14,heat:12,med:4,scrap:0},player:{x:7.4,y:8.7,a:-Math.PI/2,bob:0,steps:0},people,policies:{children:{food:100,heat:100},essential:{food:100,heat:100},general:{food:75,heat:75},elderly:{food:75,heat:75}},fieldLog:[{time:360,text:'File opened. Thirty residents remain on the district register.'}],siteUses:{},stats:{deaths:0,mutations:0,daysSurvived:0},nightReports:[]}}
function restoreRng(){rng=mulberry32(hashSeed(state.seed));const burn=(state.day*97+state.minutes+state.stats.deaths*13+state.stats.mutations*17)%700;for(let i=0;i<burn;i++)rng()}
function alive(){return state.people.filter(p=>p.alive)}
function cohortLabel(c){return({children:'Children',essential:'Essential workers',general:'General adults',elderly:'Elderly'})[c]}

function save(show=true){if(!state)return;localStorage.setItem(SAVE_KEY,JSON.stringify(state));if(show)toast('File saved');updateContinue()}
function load(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return false;state=JSON.parse(raw);if(state.version!==3)return false;restoreRng();startGameUI();return true}catch(e){console.error(e);return false}}
function updateContinue(){$('#continueBtn').disabled=!localStorage.getItem(SAVE_KEY)}
function logField(text){state.fieldLog.unshift({time:state.minutes,text});state.fieldLog=state.fieldLog.slice(0,30);renderLog()}
function addTime(m,text){state.minutes=clamp(state.minutes+m,360,1080);if(text)logField(text);if(state.minutes>=1080&&state.phase==='field')openLedger();refreshHUD()}

function startNew(){state=makeState();startGameUI();save(false);if(!localStorage.getItem(TUTORIAL_KEY))startTutorial(0);else feedback('Administration opened','Reach a marked location and inspect it.','good')}
function startGameUI(){$('#titleScreen').classList.remove('active');$('#gameScreen').classList.add('active');setPhase('field');refreshAll();resize();requestFrame()}
function setPhase(p){state.phase=p;$('#fieldView').classList.toggle('active',p==='field');$('#ledgerView').classList.toggle('active',p==='ledger');$('#phaseLabel').textContent=p==='field'?'FIELD':'TRIAGE';if(p==='field')resize()}
function refreshAll(){refreshHUD();renderLog();renderPolicies();renderLedger()}
function refreshHUD(){if(!state)return;$('#dayLabel').textContent=pad(state.day);$('#timeLabel').textContent=fmtTime(state.minutes);$('#aliveLabel').textContent=alive().length;['food','heat','med'].forEach(k=>{const v=state.stock[k].toFixed(1);const id=k==='food'?'Food':k==='heat'?'Heat':'Med';$(`#${k}Stock`).textContent=v;$(`#bag${id}`).textContent=v});$('#scrapStock').textContent=state.stock.scrap.toFixed(0);$('#ledgerFood').textContent=`${state.stock.food.toFixed(1)} F`;$('#ledgerHeat').textContent=`${state.stock.heat.toFixed(1)} H`;$('#ledgerMed').textContent=`${state.stock.med.toFixed(1)} M`;updateObjective()}
function renderLog(){$('#fieldLog').innerHTML=state?state.fieldLog.map(x=>`<p><time>${fmtTime(x.time)}</time>${escapeHtml(x.text)}</p>`).join(''):''}
function updateObjective(){if(!state)return;let t='Scavenge before dusk',b='Move through the district. Marked locations become interactable when you are close and facing them.';if(state.minutes>900){t='The light is failing';b='You have little field time left. Return to Town Hall or finish one last task.'}if(state.minutes>=1080){t='Field operations ended';b='The ledger must now be sealed.'}$('#objectiveTitle').textContent=t;$('#objectiveBody').textContent=b}

function isWall(x,y){const xi=Math.floor(x),yi=Math.floor(y);if(xi<0||yi<0||yi>=MAP.length||xi>=MAP[0].length)return 1;return MAP[yi][xi]}
function canMove(x,y){const r=.22;return !isWall(x-r,y-r)&&!isWall(x+r,y-r)&&!isWall(x-r,y+r)&&!isWall(x+r,y+r)}
function resize(){if(!canvas)return;const r=canvas.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,1.5);canvas.width=Math.max(1,Math.floor(r.width*dpr));canvas.height=Math.max(1,Math.floor(r.height*dpr));ctx.setTransform(dpr,0,0,dpr,0,0);w=r.width;h=r.height}
function requestFrame(){cancelAnimationFrame(animId);lastT=performance.now();animId=requestAnimationFrame(frame)}
function frame(t){const dt=Math.min(.04,(t-lastT)/1000||.016);lastT=t;if(state&&state.phase==='field'){updateMovement(dt);renderWorld(t);renderMiniMap()}animId=requestAnimationFrame(frame)}

function updateMovement(dt){let f=0,s=0,turn=0;if(keys.KeyW||keys.ArrowUp||touch.forward)f+=1;if(keys.KeyS||keys.ArrowDown||touch.back)f-=1;if(keys.KeyA||touch.left)s-=1;if(keys.KeyD||touch.right)s+=1;if(keys.KeyQ||touch.lookL)turn-=1;if(keys.KeyE||touch.lookR)turn+=1;state.player.a+=turn*1.7*dt;const sp=1.65*dt;let dx=(Math.cos(state.player.a)*f+Math.cos(state.player.a+Math.PI/2)*s)*sp;let dy=(Math.sin(state.player.a)*f+Math.sin(state.player.a+Math.PI/2)*s)*sp;if(dx||dy){const len=Math.hypot(f,s)||1;dx/=Math.max(1,len);dy/=Math.max(1,len);const nx=state.player.x+dx,ny=state.player.y+dy;if(canMove(nx,state.player.y))state.player.x=nx;if(canMove(state.player.x,ny))state.player.y=ny;state.player.steps+=Math.hypot(dx,dy);state.player.bob+=dt*8}nearSite=findNearSite();updateInteractionHint()}
function findNearSite(){let best=null,bd=1.35;for(const s of SITES){const dx=s.x-state.player.x,dy=s.y-state.player.y,d=Math.hypot(dx,dy);if(d<bd){let da=Math.atan2(dy,dx)-state.player.a;da=Math.atan2(Math.sin(da),Math.cos(da));if(Math.abs(da)<.9){best=s;bd=d}}}return best}
function updateInteractionHint(){const el=$('#interactionHint');if(nearSite){el.classList.remove('hidden');$('#interactionText').textContent=`Inspect ${nearSite.name}`;$('#interactionSub').textContent=nearSite.kind==='hall'?'Open the ledger or review the office':nearSite.kind==='clinic'?'Search medicine or review treatment cards':nearSite.kind==='people'?'Interview households and inspect living conditions':'Search or dismantle for supplies'}else el.classList.add('hidden')}

function renderWorld(time){ctx.clearRect(0,0,w,h);const bob=Math.sin(state.player.bob)*3;drawSkyGround(bob,time);const fov=Math.PI/2.8,cols=Math.max(180,Math.floor(w/3)),colW=w/cols;const zbuf=new Array(cols);for(let c=0;c<cols;c++){const cam=(c/cols-.5)*2;const ra=state.player.a+cam*fov/2;const hit=castRay(ra);zbuf[c]=hit.dist;drawWallColumn(c*colW,colW+1,hit,bob,ra,time)}drawWorldSprites(zbuf,fov,bob,time);drawSnow(time);drawBreath(time)}
function drawSkyGround(bob){const sky=ctx.createLinearGradient(0,0,0,h*.55);sky.addColorStop(0,'#737f7a');sky.addColorStop(.58,'#56605b');sky.addColorStop(1,'#353b36');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h*.55+bob);const g=ctx.createLinearGradient(0,h*.45,h,h);g.addColorStop(0,'#c9c8bd');g.addColorStop(.32,'#a3a49b');g.addColorStop(1,'#565952');ctx.fillStyle=g;ctx.fillRect(0,h*.45+bob,w,h);ctx.fillStyle='rgba(255,255,255,.06)';for(let i=0;i<9;i++){const y=h*.55+i*i*4+bob;ctx.fillRect(0,y,w,1)}ctx.fillStyle='rgba(24,27,23,.22)';ctx.fillRect(0,h*.49+bob,w,5)}
function castRay(a){const ox=state.player.x,oy=state.player.y,dx=Math.cos(a),dy=Math.sin(a);let mx=Math.floor(ox),my=Math.floor(oy);const ddx=Math.abs(1/(dx||.0001)),ddy=Math.abs(1/(dy||.0001));let sx,sy,sdx,sdy;if(dx<0){sx=-1;sdx=(ox-mx)*ddx}else{sx=1;sdx=(mx+1-ox)*ddx}if(dy<0){sy=-1;sdy=(oy-my)*ddy}else{sy=1;sdy=(my+1-oy)*ddy}let side=0,wall=0;for(let i=0;i<40;i++){if(sdx<sdy){sdx+=ddx;mx+=sx;side=0}else{sdy+=ddy;my+=sy;side=1}wall=(MAP[my]&&MAP[my][mx])||1;if(wall)break}let dist=side===0?(mx-ox+(1-sx)/2)/(dx||.0001):(my-oy+(1-sy)/2)/(dy||.0001);dist=Math.max(.05,Math.abs(dist));let wx=side===0?oy+dist*dy:ox+dist*dx;wx-=Math.floor(wx);return{dist,wall,side,wx,mx,my}}
function drawWallColumn(x,cw,hit,bob,a,time){const corrected=hit.dist*Math.cos(a-state.player.a);const wh=Math.min(h*1.7,h/corrected*.78),top=h*.5-wh/2+bob;let base=hit.wall===1?[92,86,74]:hit.wall===2?[91,72,53]:hit.wall===3?[100,104,97]:[71,75,66];let shade=clamp(1-corrected/12,.25,1)*(hit.side?.78:1);const mortar=(Math.floor(hit.wx*9)%3===0)?-13:0;const r=Math.floor((base[0]+mortar)*shade),g=Math.floor((base[1]+mortar)*shade),b=Math.floor((base[2]+mortar)*shade);ctx.fillStyle=`rgb(${r},${g},${b})`;ctx.fillRect(x,top,cw,wh);if(corrected<7){ctx.fillStyle=`rgba(20,22,18,${clamp((7-corrected)/18,0,.28)})`;const course=Math.floor((top+time*.002)%22);for(let yy=top-course;yy<top+wh;yy+=22)ctx.fillRect(x,yy,cw,1);if(hit.wall===3&&hit.wx>.28&&hit.wx<.72){const mid=top+wh*.43;ctx.fillStyle=`rgba(15,18,16,${clamp(.65-corrected*.04,.18,.55)})`;ctx.fillRect(x,mid,cw,Math.max(3,wh*.14))}}const fog=clamp((corrected-4)/10,0,.82);if(fog>0){ctx.fillStyle=`rgba(154,163,156,${fog})`;ctx.fillRect(x,top,cw,wh)}}
function projectSprite(px,py,fov,bob){const dx=px-state.player.x,dy=py-state.player.y,dist=Math.hypot(dx,dy);let ang=Math.atan2(dy,dx)-state.player.a;ang=Math.atan2(Math.sin(ang),Math.cos(ang));if(Math.abs(ang)>fov*.72)return null;const sx=w/2+(ang/(fov/2))*w/2;return{sx,dist,y:h*.5+bob}}
function drawWorldSprites(zbuf,fov,bob,time){const sprites=[];for(const s of SITES)sprites.push({type:'site',...s});const living=alive();NPC_POINTS.forEach((p,i)=>sprites.push({type:'npc',x:p.x,y:p.y,name:living[(i*5+state.day)%Math.max(1,living.length)]?.name||'Resident',idx:i}));sprites.sort((a,b)=>Math.hypot(b.x-state.player.x,b.y-state.player.y)-Math.hypot(a.x-state.player.x,a.y-state.player.y));for(const s of sprites){const p=projectSprite(s.x,s.y,fov,bob);if(!p||p.dist>12)continue;const col=clamp(Math.floor((p.sx/w)*zbuf.length),0,zbuf.length-1);if(zbuf[col]&&p.dist>zbuf[col]+.2)continue;if(s.type==='site')drawSiteSprite(s,p,time);else drawNpcSprite(s,p,time)}}
function drawSiteSprite(s,p,time){const size=clamp(130/p.dist,18,105),pulse=1+Math.sin(time*.004+s.x)*.04;ctx.save();ctx.translate(p.sx,p.y-size*.12);ctx.globalAlpha=clamp(1-(p.dist-6)/7,.25,1);ctx.strokeStyle=s.accent;ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,-size*.45,size*.16*pulse,0,Math.PI*2);ctx.stroke();ctx.fillStyle='rgba(14,16,13,.75)';ctx.fillRect(-size*.7,-size*.25,size*1.4,size*.32);ctx.fillStyle='#ece9dc';ctx.font=`700 ${clamp(26/p.dist,10,15)}px system-ui`;ctx.textAlign='center';ctx.fillText(s.name,0,-size*.04);ctx.restore()}
function drawNpcSprite(s,p,time){const H=clamp(145/p.dist,20,120),sway=Math.sin(time*.003+s.idx)*H*.025;ctx.save();ctx.translate(p.sx+sway,p.y+H*.35);ctx.globalAlpha=clamp(1-(p.dist-5)/8,.28,.95);ctx.fillStyle='#292b28';ctx.beginPath();ctx.ellipse(0,-H*.64,H*.11,H*.11,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#343731';ctx.beginPath();ctx.moveTo(-H*.18,-H*.51);ctx.lineTo(H*.18,-H*.51);ctx.lineTo(H*.24,0);ctx.lineTo(-H*.24,0);ctx.closePath();ctx.fill();ctx.strokeStyle='#60665f';ctx.lineWidth=Math.max(1,H*.012);ctx.beginPath();ctx.moveTo(-H*.08,0);ctx.lineTo(-H*.12,H*.27);ctx.moveTo(H*.08,0);ctx.lineTo(H*.12,H*.27);ctx.stroke();if(p.dist<2.2){ctx.fillStyle='rgba(10,11,9,.75)';ctx.fillRect(-H*.55,-H*.96,H*1.1,H*.2);ctx.fillStyle='#d5d7cf';ctx.font=`${Math.max(9,H*.07)}px system-ui`;ctx.textAlign='center';ctx.fillText(s.name,0,-H*.82)}ctx.restore()}
function drawSnow(time){ctx.fillStyle='rgba(244,246,242,.78)';for(let i=0;i<95;i++){const speed=18+(i%7)*7;const x=(i*83+time*.025*(i%3+1))%(w+30)-15;const y=(i*47+time*.02*speed)%(h+30)-15;const s=i%9===0?2:1;ctx.fillRect(x,y,s,s)}ctx.fillStyle='rgba(220,226,221,.07)';ctx.fillRect(0,0,w,h)}
function drawBreath(time){if(Math.sin(time*.0017)>-.55){const a=(Math.sin(time*.0017)+.55)/1.55*.07;ctx.fillStyle=`rgba(235,238,234,${a})`;ctx.beginPath();ctx.ellipse(w*.5,h*.76,w*.16,h*.045,0,0,Math.PI*2);ctx.fill()}}
function renderMiniMap(){if(!mapCtx)return;const cw=mapCanvas.width,ch=mapCanvas.height,ts=cw/MAP[0].length;mapCtx.fillStyle='#11140f';mapCtx.fillRect(0,0,cw,ch);for(let y=0;y<MAP.length;y++)for(let x=0;x<MAP[y].length;x++){if(MAP[y][x]){mapCtx.fillStyle=MAP[y][x]===3?'#6f756e':MAP[y][x]===2?'#6c5543':'#53574e';mapCtx.fillRect(x*ts,y*ts,ts,ts)}}for(const s of SITES){mapCtx.fillStyle=s.accent;mapCtx.beginPath();mapCtx.arc(s.x*ts,s.y*ts,2.6,0,Math.PI*2);mapCtx.fill()}mapCtx.fillStyle='#f0ead6';mapCtx.beginPath();mapCtx.arc(state.player.x*ts,state.player.y*ts,3,0,Math.PI*2);mapCtx.fill();mapCtx.strokeStyle='#f0ead6';mapCtx.beginPath();mapCtx.moveTo(state.player.x*ts,state.player.y*ts);mapCtx.lineTo((state.player.x+Math.cos(state.player.a)*1.1)*ts,(state.player.y+Math.sin(state.player.a)*1.1)*ts);mapCtx.stroke()}

function interact(){if(state.phase!=='field')return;if(nearSite)inspectSite(nearSite);else feedback('Nothing within reach','Move closer to a marked location and face it.','bad')}
function inspectSite(site){const actions=[];if(site.kind==='hall'){actions.push({label:'Open population ledger',detail:'Begin evening triage',run:openLedger});actions.push({label:'Review the office',detail:'15 min · records',run:()=>{addTime(15,'Town Hall: reviewed conflicting residency records.');assessResidents(1,0,'Town Hall',false);feedback('Records compared','One resident record is now more reliable.','good')}})}if(site.kind==='loot'){actions.push({label:'Search rooms and containers',detail:'45 min · food / heat / scrap',run:()=>scavenge(site,45,'search')});actions.push({label:'Dismantle usable material',detail:'90 min · heat / scrap',run:()=>scavenge(site,90,'dismantle')})}if(site.kind==='clinic'){actions.push({label:'Search pharmacy cabinets',detail:'60 min · medicine',run:()=>scavenge(site,60,'clinic')});actions.push({label:'Review treatment cards',detail:'35 min · assess 3 residents',run:()=>assessResidents(3,35,site.name)})}if(site.kind==='people'){actions.push({label:'Interview a household',detail:'35 min · assess 1 resident',run:()=>assessResidents(1,35,site.name)});actions.push({label:'Inspect rooms and stove',detail:'50 min · supplies / intelligence',run:()=>scavenge(site,50,'people')})}showModal(`<div class="eyebrow">${escapeHtml(site.kind)} · ${fmtTime(state.minutes)}</div><h2>${escapeHtml(site.name)}</h2><p>${escapeHtml(site.desc)}</p><div class="action-list">${actions.map((a,i)=>`<button data-act="${i}"><span>${escapeHtml(a.label)}</span><small>${escapeHtml(a.detail)}</small></button>`).join('')}</div><button class="ghost wide modal-close">Leave</button>`);actions.forEach((a,i)=>$(`[data-act="${i}"]`).onclick=()=>{hideModal();a.run()});$('.modal-close').onclick=hideModal}
function scavenge(site,min,type){const uses=state.siteUses[site.id]||0;state.siteUses[site.id]=uses+1;const dep=Math.max(.2,1-uses*.23);let food=0,heat=0,med=0,scrap=0;if(type==='search'){food=+(randInt(1,5)*dep).toFixed(1);heat=+(randInt(0,3)*dep).toFixed(1);scrap=randInt(0,2)}if(type==='dismantle'){heat=+(randInt(2,6)*dep).toFixed(1);scrap=randInt(2,5)}if(type==='clinic'){med=+(randInt(1,4)*dep).toFixed(1);food=rand()<.25?1:0}if(type==='people'){food=+(randInt(0,3)*dep).toFixed(1);heat=+(randInt(0,2)*dep).toFixed(1);if(rand()<.38)assessResidents(1,0,site.name,false)}state.stock.food+=food;state.stock.heat+=heat;state.stock.med+=med;state.stock.scrap+=scrap;addTime(min,`${site.name}: recovered ${food} nutrition, ${heat} heat, ${med} medicine, ${scrap} scrap.`);screenFlash('loot');feedback('Supplies recovered',`+${food} food · +${heat} heat · +${med} medicine · +${scrap} scrap`,'good');save(false);advanceTutorialByAction('scavenge')}
function assessResidents(count,min,source,log=true){const unknown=alive().filter(p=>!p.assessed),picked=[];for(let i=0;i<count&&unknown.length;i++){const ix=Math.floor(rand()*unknown.length);const p=unknown.splice(ix,1)[0];p.assessed=true;picked.push(p)}if(min)addTime(min,`${source}: ${picked.map(p=>p.name).join(', ')||'no new residents'} assessed.`);else if(log&&picked.length)logField(`${source}: ${picked.map(p=>p.name).join(', ')} assessed.`);if(picked.length){feedback('Information improved',picked.map(p=>p.name).join(' · '),'good');advanceTutorialByAction('assess')}save(false)}
function screenFlash(type){const fx=$('#screenFx');fx.className=`screen-fx ${type}`;clearTimeout(flashTimer);flashTimer=setTimeout(()=>fx.className='screen-fx',240)}
function feedback(title,sub,type=''){const box=document.createElement('div');box.className=`feedback-item ${type}`;box.innerHTML=`<b>${escapeHtml(title)}</b><small>${escapeHtml(sub)}</small>`;$('#feedbackFeed').prepend(box);setTimeout(()=>box.remove(),4000)}

function openLedger(){if(state.phase==='ledger')return;setPhase('ledger');applyPolicyDefaults();renderPolicies();renderLedger();save(false);advanceTutorialByAction('ledger')}
function closeLedger(){if(state.minutes>=1080){toast('Field operations have ended for the day');return}setPhase('field')}
function renderPolicies(){if(!state)return;const gs=['children','essential','general','elderly'];$('#policyGrid').innerHTML=gs.map(g=>{const c=alive().filter(p=>p.cohort===g).length,pol=state.policies[g];return`<section class="policy-card" data-cohort="${g}"><header><span>${cohortLabel(g)}</span><small>${c} alive</small></header><label class="policy-line"><span>Food</span><input data-pol="food" type="range" min="0" max="125" step="25" value="${pol.food}"><output>${pol.food}%</output></label><label class="policy-line"><span>Heat</span><input data-pol="heat" type="range" min="0" max="125" step="25" value="${pol.heat}"><output>${pol.heat}%</output></label></section>`}).join('');$$('.policy-card input').forEach(inp=>inp.oninput=()=>{const card=inp.closest('.policy-card'),g=card.dataset.cohort,k=inp.dataset.pol;state.policies[g][k]=Number(inp.value);inp.nextElementSibling.textContent=`${inp.value}%`;applyPolicyDefaults();renderLedger()})}
function applyPolicyDefaults(){alive().forEach(p=>{const pol=state.policies[p.cohort];if(!p.ration.manualFood)p.ration.food=pol.food/100;if(!p.ration.manualHeat)p.ration.heat=pol.heat/100})}
function mutObj(p){return p.mutation?MUTATIONS.find(m=>m.name===p.mutation):null}
function requestedTotals(){return alive().reduce((a,p)=>{const m=mutObj(p);a.food+=p.ration.food*(m?.food||1);a.heat+=p.ration.heat*(m?.heat||1);a.med+=p.ration.med?1:0;return a},{food:0,heat:0,med:0})}
function condition(p){if(!p.alive)return`Dead · ${p.causeOfDeath}`;if(!p.assessed)return p.health<35?'Visibly poor':p.health<60?'Uncertain':'Appears stable';return p.health<25?'Critical':p.health<50?'Poor':p.health<75?'Strained':'Stable'}
function renderLedger(){if(!state)return;const q=($('#residentSearch').value||'').toLowerCase(),f=$('#residentFilter').value;const list=state.people.filter(p=>{if(q&&!(p.name+' '+p.job).toLowerCase().includes(q))return false;if(f==='critical'&&!(p.alive&&p.health<40))return false;if(f==='dissent'&&!(p.alive&&p.dissent>=60))return false;if(f==='known'&&!p.assessed)return false;if(f==='mutated'&&!p.mutation)return false;return true});$('#residentCards').innerHTML=list.map(p=>{const exact=p.assessed||!p.alive;return`<article class="resident-card ${!p.alive?'dead':''} ${p.dissent>70?'high-dissent':''}" data-id="${p.id}"><div class="resident-head"><div><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.job)} · age ${p.age}</small></div><span class="pill">${cohortLabel(p.cohort)}</span></div><div class="resident-meta"><span class="pill">${escapeHtml(condition(p))}</span>${p.assessed?'<span class="pill">ASSESSED</span>':''}${p.mutation?`<span class="pill">${escapeHtml(p.mutation)}</span>`:''}</div><div class="resident-state"><span>Health: ${exact?Math.round(p.health)+'%':'unknown'}</span><span>Dissent: ${exact?Math.round(p.dissent)+'%':p.dissent>55?'high?':'uncertain'}</span></div>${p.alive?`${allocRow(p,'food','Food')}${allocRow(p,'heat','Heat')}<label class="med-line"><input type="checkbox" data-med="${p.id}" ${p.ration.med?'checked':''}> Medicine tonight</label>`:''}</article>`}).join('');$$('[data-adjust]').forEach(b=>b.onclick=()=>adjust(Number(b.dataset.id),b.dataset.adjust,Number(b.dataset.delta)));$$('[data-med]').forEach(c=>c.onchange=()=>{const p=state.people.find(x=>x.id===Number(c.dataset.med));p.ration.med=c.checked;updateProjection()});updateProjection()}
function allocRow(p,k,label){return`<div class="alloc-row"><span>${label}</span><div class="ctrl"><button data-adjust="${k}" data-id="${p.id}" data-delta="-.25">−</button><b>${Math.round(p.ration[k]*100)}%</b><button data-adjust="${k}" data-id="${p.id}" data-delta=".25">+</button></div><small>${p.ration[k]===0?'none':p.ration[k]<.75?'low':p.ration[k]>=1?'full':'reduced'}</small></div>`}
function adjust(id,k,d){const p=state.people.find(x=>x.id===id);if(!p)return;p.ration[k]=clamp(p.ration[k]+d,0,1.5);p.ration[k==='food'?'manualFood':'manualHeat']=true;renderLedger()}
function updateProjection(){const t=requestedTotals(),over=t.food>state.stock.food+.001||t.heat>state.stock.heat+.001||t.med>state.stock.med+.001;const el=$('#projectionText');el.className=`projection ${over?'over':'ok'}`;el.innerHTML=`Requested <b>${t.food.toFixed(1)}</b> food · <b>${t.heat.toFixed(1)}</b> heat · <b>${t.med.toFixed(0)}</b> medicine — <strong>${over?'PLAN EXCEEDS STOCK':'PLAN FITS STOCK'}</strong>`;$('#sealLedgerBtn').disabled=over}
function fitPlan(){const a=alive();a.forEach(p=>{p.ration.food=.5;p.ration.heat=.5;p.ration.manualFood=true;p.ration.manualHeat=true});let t=requestedTotals();let guard=0;while(guard++<400){let changed=false;for(const p of [...a].sort((x,y)=>priority(y)-priority(x))){if(t.food+.25<=state.stock.food&&p.ration.food<1){p.ration.food+=.25;changed=true}if(t.heat+.25<=state.stock.heat&&p.ration.heat<1){p.ration.heat+=.25;changed=true}t=requestedTotals()}if(!changed)break}renderLedger();feedback('Plan fitted','A conservative allocation now fits available stock.','good')}
function priority(p){return(p.cohort==='children'?4:p.cohort==='essential'?3:p.cohort==='general'?2:1)+(100-p.health)/100}
function autoMedicine(){alive().forEach(p=>p.ration.med=false);[...alive()].sort((a,b)=>a.health-b.health).slice(0,Math.floor(state.stock.med)).forEach(p=>p.ration.med=true);renderLedger()}

function resolveNight(){const t=requestedTotals();if(t.food>state.stock.food+.001||t.heat>state.stock.heat+.001||t.med>state.stock.med+.001){toast('Requested allocations exceed stock');return}state.stock.food=Math.max(0,state.stock.food-t.food);state.stock.heat=Math.max(0,state.stock.heat-t.heat);state.stock.med=Math.max(0,state.stock.med-t.med);showNightCurtain();setTimeout(()=>{const report=[],deaths=[],mutations=[];for(const p of [...alive()]){const m=mutObj(p),fr=p.ration.food/(m?.food||1),hr=p.ration.heat/(m?.heat||1);p.hunger=clamp(p.hunger+(fr-.8)*25,0,100);p.warmth=clamp(p.warmth+(hr-.75)*28,0,100);p.rad=+(p.rad+.18+(p.warmth<40?.12:0)+(p.district==='Industrial Fringe'?.10:0)).toFixed(2);let damage=0;if(p.hunger<35)damage+=(35-p.hunger)*.28;if(p.warmth<35)damage+=(35-p.warmth)*.34;if(p.rad>4)damage+=(p.rad-4)*1.2;if(p.ration.med&&p.health<85)p.health+=randInt(7,15);p.health=clamp(p.health-damage+randInt(-3,2),0,100);if(fr<.6)p.dissent+=randInt(6,12);else if(fr>=1)p.dissent-=randInt(1,4);if(hr<.6)p.dissent+=randInt(4,9);p.dissent=clamp(p.dissent+(m?.aura||0),0,100);if(!p.mutation){const reserve=Math.max(12,p.hunger),exposure=p.rad*(1+(100-p.health)/90),prob=1-Math.exp(-.0075*((exposure*state.day)/(reserve/50)));if(rand()<prob){const mu=choice(MUTATIONS);p.mutation=mu.name;state.stats.mutations++;mutations.push(`${p.name}: ${mu.name}`);p.history.push({day:state.day,event:`Mutation: ${mu.name}`})}}let cause=null;if(p.health<=3)cause=p.warmth<25?'hypothermia':p.hunger<25?'starvation':'systemic collapse';else if(p.health<22&&rand()<.11)cause=p.warmth<p.hunger?'hypothermia':'starvation';if(cause){p.alive=false;p.causeOfDeath=cause;p.dayOfDeath=state.day;state.stats.deaths++;deaths.push(`${p.name} — ${cause}`);p.history.push({day:state.day,event:`Died: ${cause}`})}}if(alive().some(p=>p.dissent>78)&&rand()<.42){const suspect=choice(alive().filter(p=>p.dissent>65));const loss=Math.min(state.stock.food,randInt(1,3));state.stock.food-=loss;report.push(`Inventory discrepancy: ${loss} nutrition missing. ${suspect.name} appears in two conflicting witness accounts.`)}report.push(...mutations.map(x=>`Mutation recorded: ${x}`),...deaths.map(x=>`Death recorded: ${x}`));state.nightReports.push({day:state.day,report});state.stats.daysSurvived=state.day;hideNightCurtain();showNightReport(report,deaths,mutations)},1100)}
function showNightCurtain(){$('#nightCurtain').classList.remove('hidden')}
function hideNightCurtain(){$('#nightCurtain').classList.add('hidden')}
function showNightReport(report,deaths,mutations){const lines=report.length?report:['No major incident was officially recorded.'];showModal(`<div class="eyebrow">MORNING REPORT · DAY ${state.day+1}</div><h2>${deaths.length?`${deaths.length} resident${deaths.length>1?'s':''} died during the night`:'The district survived the night'}</h2><p>${mutations.length?`${mutations.length} new biological anomaly${mutations.length>1?'ies were':' was'} entered into the registry.`:'No new mutation was formally recorded.'}</p><div class="action-list">${lines.map(l=>`<div style="padding:10px;border-left:3px solid ${l.startsWith('Death')?'#9b4b40':l.startsWith('Mutation')?'#998a57':'#68746a'};background:#11140f">${escapeHtml(l)}</div>`).join('')}</div><button id="nextDayBtn" class="primary wide">Begin Next Day</button>`);$('#nextDayBtn').onclick=()=>{hideModal();advanceDay()}}
function advanceDay(){if(state.day>=GAME_DAYS||alive().length===0){endGame();return}state.day++;state.minutes=360;state.phase='field';state.player={x:7.4,y:8.7,a:-Math.PI/2,bob:0,steps:0};alive().forEach(p=>{p.ration={food:1,heat:1,med:false};if(rand()<.08)p.assessed=false});setPhase('field');refreshAll();save(false);feedback(`Day ${state.day}`,`${alive().length} residents remain on the register.`,'good')}
function endGame(){showModal(`<div class="eyebrow">FINAL ADMINISTRATIVE POST-MORTEM</div><h2>The registry is closed.</h2><p>Initial population: 30 · Final population: ${alive().length} · Deaths: ${state.stats.deaths} · Mutations: ${state.stats.mutations} · Days administered: ${state.stats.daysSurvived}</p><div class="action-list"><button id="exportBtn">Export obituary CSV</button><button id="restartBtn">Begin another administration</button></div>`);$('#exportBtn').onclick=exportCSV;$('#restartBtn').onclick=()=>{hideModal();startNew()}}
function exportCSV(){const rows=[['id','name','age','occupation','alive','cause_of_death','day_of_death','mutation','health','dissent','radiation'],...state.people.map(p=>[p.id,p.name,p.age,p.job,p.alive,p.causeOfDeath||'',p.dayOfDeath||'',p.mutation||'',p.health.toFixed(1),p.dissent.toFixed(1),p.rad.toFixed(2)])];const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`winter-registry-${state.seed}.csv`;a.click();URL.revokeObjectURL(a.href)}

function showModal(html){$('#modalCard').innerHTML=html;$('#modalLayer').classList.remove('hidden')}
function hideModal(){$('#modalLayer').classList.add('hidden')}
function toast(t){const e=$('#toast');e.textContent=t;e.classList.remove('hidden');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.add('hidden'),2200)}

const TUTORIAL=[
{title:'You are physically in the district now',body:'This version is first person. Walk with WASD or the touch pad. Turn with Q/E, click-drag, or the curved-arrow buttons.',action:'Continue'},
{title:'Find a marked location',body:'Site names appear in the world and on the small map. Walk toward one until the INTERACT prompt appears.',action:'Show me a nearby site',run:()=>faceNearestSite()},
{title:'Actions cost daylight',body:'Searching a room, interviewing a household and crossing the district all consume the same finite day. The clock at the top is part of the survival system.',action:'Continue'},
{title:'Get supplies or information',body:'Interact with a warehouse, workshop, clinic or household. Supplies change immediately and the screen will now visibly react to successful actions.',action:'Continue'},
{title:'Information is survival',body:'Residents you assess reveal exact condition and dissent in the ledger. Unassessed people remain estimates, and those estimates can mislead you.',action:'Continue'},
{title:'Return to Town Hall',body:'At any point you can return to the ledger. At 18:00 field operations end automatically.',action:'Open ledger',run:()=>openLedger()},
{title:'Set tonight’s policy',body:'Group sliders set defaults. Resident cards let you override food, heat and medicine. The projection panel turns red if the plan exceeds stock.',action:'Continue'},
{title:'Seal the ledger',body:'Once the plan fits, end the day. The night resolves hunger, cold, radiation, dissent, death and mutation. Tomorrow you walk through what remains.',action:'Finish tutorial',run:()=>{localStorage.setItem(TUTORIAL_KEY,'done');stopTutorial()}}
];
function startTutorial(step=0){tutorial={active:true,step};renderTutorial()}
function renderTutorial(){const s=TUTORIAL[tutorial.step];if(!s)return stopTutorial();$('#tutorialCard').innerHTML=`<div class="step">GUIDED ORIENTATION · ${tutorial.step+1}/${TUTORIAL.length}</div><h2>${escapeHtml(s.title)}</h2><p>${escapeHtml(s.body)}</p><div class="tutorial-actions"><button id="tutorialSkip" class="ghost">Skip</button><button id="tutorialNext" class="primary">${escapeHtml(s.action)}</button></div>`;$('#tutorialLayer').classList.remove('hidden');$('#tutorialSkip').onclick=()=>{localStorage.setItem(TUTORIAL_KEY,'done');stopTutorial()};$('#tutorialNext').onclick=()=>{if(s.run)s.run();if(tutorial.active){tutorial.step++;if(tutorial.step<TUTORIAL.length)renderTutorial();else stopTutorial()}}}
function stopTutorial(){tutorial.active=false;$('#tutorialLayer').classList.add('hidden')}
function advanceTutorialByAction(a){if(!tutorial.active)return;if((a==='scavenge'&&tutorial.step===3)||(a==='assess'&&tutorial.step===4)||(a==='ledger'&&tutorial.step===5)){tutorial.step++;renderTutorial()}}
function faceNearestSite(){let best=SITES[0],bd=1e9;for(const s of SITES){const d=Math.hypot(s.x-state.player.x,s.y-state.player.y);if(d<bd){bd=d;best=s}}state.player.a=Math.atan2(best.y-state.player.y,best.x-state.player.x);stopTutorial();feedback('Nearest site highlighted',`${best.name} is now directly ahead.`,'good');setTimeout(()=>startTutorial(2),1400)}

function registerPWA(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(console.warn);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('#installBtn').classList.add('hidden')}}
function bind(){canvas=$('#world');ctx=canvas.getContext('2d');mapCanvas=$('#mapCanvas');mapCtx=mapCanvas.getContext('2d');$('#newGameBtn').onclick=startNew;$('#continueBtn').onclick=()=>{if(load())feedback('File restored','Continue the current day.','good');else toast('No compatible 0.3 save found')};$('#saveBtn').onclick=()=>save(true);$('#helpBtn').onclick=()=>startTutorial(0);$('#interactBtn').onclick=interact;$('#townHallBtn').onclick=openLedger;$('#backToFieldBtn').onclick=closeLedger;$('#sealLedgerBtn').onclick=resolveNight;$('#fitPlanBtn').onclick=fitPlan;$('#autoMedicineBtn').onclick=autoMedicine;$('#residentSearch').oninput=renderLedger;$('#residentFilter').onchange=renderLedger;$('#modalLayer').addEventListener('pointerdown',e=>{if(e.target===$('#modalLayer'))hideModal()});window.addEventListener('resize',resize);window.addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyF'){e.preventDefault();interact()}});window.addEventListener('keyup',e=>keys[e.code]=false);canvas.addEventListener('pointerdown',e=>{dragging=true;lastPointerX=e.clientX;canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!dragging||!state)return;const dx=e.clientX-lastPointerX;lastPointerX=e.clientX;state.player.a+=dx*.006});canvas.addEventListener('pointerup',()=>dragging=false);$$('[data-move]').forEach(b=>{const k=b.dataset.move;const on=()=>touch[k]=true,off=()=>touch[k]=false;b.addEventListener('pointerdown',on);['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,off))});$$('[data-look]').forEach(b=>{const k=b.dataset.look==='left'?'lookL':'lookR';const on=()=>touch[k]=true,off=()=>touch[k]=false;b.addEventListener('pointerdown',on);['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,off))});updateContinue();registerPWA()}
document.addEventListener('DOMContentLoaded',bind);
})();