const PROGRAMMES = {
            'coma': { name: "THE COMA", cat: "SEDATIVES", desc: "4Hz -> 0.5Hz Delta Slide. Brown Noise.", freqStart: 4, freqEnd: 0.5, duration: 2700, engine: 'binaural', noise: 'brown', strobe: 'off', color: '#000000', man: { goal: "Total Unconsciousness", audio: "Binaural Slide", visual: "Blackout" } },
            'anaesthesia': { name: "ANAESTHESIA", cat: "SEDATIVES", desc: "2.5Hz Isochronic. Pain Mgmt.", freqStart: 2.5, freqEnd: 2.5, duration: 1800, engine: 'isochronic', noise: 'pink', strobe: 'sine', color: '#8F00FF', man: { goal: "Dissociation", audio: "2.5Hz Isochronic", visual: "Violet Pulse" } },
            'womb': { name: "THE WOMB", cat: "SEDATIVES", desc: "60Hz Heartbeat. Regression.", freqStart: 0, freqEnd: 0, duration: 1200, engine: 'heartbeat', noise: 'lpf-pink', strobe: 'static', color: '#FFBF00', man: { goal: "Safety/Anxiety Removal", audio: "Heartbeat + Pink Noise", visual: "Amber Static" } },
            'reset': { name: "THE RESET", cat: "SEDATIVES", desc: "10Hz Alpha Lock. Power Nap.", freqStart: 10, freqEnd: 10, duration: 1200, engine: 'isochronic', noise: 'pink', strobe: 'square', color: '#00FF00', man: { goal: "No Sleep Inertia", audio: "10Hz Alpha", visual: "Green Flicker" } },
            'hgh': { name: "HGH RELEASE", cat: "SEDATIVES", desc: "1.05Hz Binaural. Recovery.", freqStart: 1.05, freqEnd: 1.05, duration: 2400, engine: 'binaural', noise: 'none', strobe: 'off', color: '#000000', man: { goal: "Pituitary Stim", audio: "1.05Hz Binaural", visual: "Off" } },
            'sniper': { name: "THE SNIPER", cat: "FOCUS", desc: "14Hz SMR. Stabilisation.", freqStart: 14, freqEnd: 14, duration: 3600, engine: 'isochronic', noise: 'none', strobe: 'dot-only', color: '#0000FF', man: { goal: "SMR Focus", audio: "14Hz Pulse", visual: "Blue Dot" } },
            'flow': { name: "FLOW STATE", cat: "FOCUS", desc: "12-15Hz Ramp. Polymeter.", freqStart: 12, freqEnd: 15, duration: 5400, engine: 'polymeter', noise: 'none', strobe: 'subtle', color: '#FFFFFF', man: { goal: "Deep Work", audio: "Polymeter Ramp", visual: "Subtle White" } },
            'highvolt': { name: "HIGH VOLTAGE", cat: "FOCUS", desc: "20Hz Beta. Adrenaline.", freqStart: 18, freqEnd: 20, duration: 900, engine: 'distorted', noise: 'white', strobe: 'square', color: '#FF0000', man: { goal: "Psych Up", audio: "Distorted Beta", visual: "Hard Red" } },
            'reader': { name: "SPEED READER", cat: "FOCUS", desc: "40Hz Gamma. Binding.", freqStart: 40, freqEnd: 40, duration: 1200, engine: 'gamma-burst', noise: 'white', strobe: 'square', color: '#FFFFFF', man: { goal: "Data Intake", audio: "Gamma Burst", visual: "Bright White" } },
            'math': { name: "MATHEMATICIAN", cat: "FOCUS", desc: "13Hz Monaural. Logic.", freqStart: 13, freqEnd: 13, duration: 3600, engine: 'monaural', noise: 'none', strobe: 'geo', color: '#00FFFF', man: { goal: "Analytical Thinking", audio: "13Hz Monaural", visual: "Cyan Geometry" } },
            'hypnagogia': { name: "HYPNAGOGIA", cat: "PSYCHONAUTICS", desc: "6Hz Theta. Confusion.", freqStart: 7, freqEnd: 6, duration: 1800, engine: 'confusion', noise: 'none', strobe: 'square', color: '#FFFFFF', man: { goal: "Twilight State", audio: "Confusion Tech", visual: "Fractal Strobe" } },
            'lucid': { name: "LUCID DREAM", cat: "PSYCHONAUTICS", desc: "Silence -> 40Hz Pings.", freqStart: 0, freqEnd: 40, duration: 1800, engine: 'lucid-protocol', noise: 'none', strobe: 'lucid', color: '#FF0000', man: { goal: "REM Entry", audio: "Silence + Pings", visual: "Red Flashes" } },
            'ego': { name: "EGO DISSOLUTION", cat: "PSYCHONAUTICS", desc: "Shepard Tone. The Void.", freqStart: 0, freqEnd: 0, duration: 3600, engine: 'shepard', noise: 'reverb', strobe: 'troxler-void', color: '#444444', man: { goal: "Ego Death", audio: "Infinite Reverb", visual: "Troxler Fade" } },
            'time': { name: "TIME DILATION", cat: "PSYCHONAUTICS", desc: "Granular Synthesis.", freqStart: 0, freqEnd: 0, duration: 600, engine: 'granular', noise: 'none', strobe: 'sine', color: '#333333', man: { goal: "Distortion", audio: "Time Stretch", visual: "Slow Motion" } },
            'oracle': { name: "THE ORACLE", cat: "PSYCHONAUTICS", desc: "Random Theta/Alpha.", freqStart: 5, freqEnd: 10, duration: 2400, engine: 'random-hop', noise: 'pink', strobe: 'kaleido', color: 'random', man: { goal: "Divergent Thinking", audio: "Random Hop", visual: "Kaleidoscope" } },
            'panic': { name: "PANIC BUTTON", cat: "EMOTIONAL", desc: "0.1Hz Vagal Pacing.", freqStart: 0.1, freqEnd: 0.1, duration: 600, engine: 'vagal', noise: 'none', strobe: 'breathe', color: '#0088FF', man: { goal: "Anxiolytic", audio: "Vagal Tone", visual: "Blue Breath" } },
            'euphoria': { name: "EUPHORIA", cat: "EMOTIONAL", desc: "Major Scales + Gamma.", freqStart: 40, freqEnd: 40, duration: 1200, engine: 'chords-major', noise: 'none', strobe: 'square', color: '#FFD700', man: { goal: "The Rush", audio: "Major Chords", visual: "Gold Strobe" } },
            'stoic': { name: "THE STOIC", cat: "EMOTIONAL", desc: "100Hz Drone. Greyscale.", freqStart: 100, freqEnd: 100, duration: 1800, engine: 'drone', noise: 'none', strobe: 'static-grey', color: '#888888', man: { goal: "Blunting", audio: "Flatline Drone", visual: "Greyscale" } },
            'grieve': { name: "THE GRIEVE", cat: "EMOTIONAL", desc: "Minor Chords + Rain.", freqStart: 4, freqEnd: 4, duration: 1800, engine: 'chords-minor', noise: 'rain', strobe: 'sine', color: '#4B0082', man: { goal: "Catharsis", audio: "Minor 9th Chords", visual: "Indigo Rain" } },
            'schumann': { name: "SCHUMANN RES", cat: "EMOTIONAL", desc: "7.83Hz Earth Sync.", freqStart: 7.83, freqEnd: 7.83, duration: 1800, engine: 'isochronic', noise: 'pink', strobe: 'sine', color: '#228B22', man: { goal: "Grounding", audio: "7.83Hz Pulse", visual: "Forest Green" } },
            'oobe': { name: "OUT OF BODY", cat: "ESOTERIC", desc: "Phase Cancellation.", freqStart: 4, freqEnd: 4, duration: 2400, engine: 'phase-cancel', noise: 'brown', strobe: 'tunnel', color: '#FFFFFF', man: { goal: "Dissociation", audio: "Phase Cancel", visual: "Tunnel" } },
            'third': { name: "THIRD EYE", cat: "ESOTERIC", desc: "963Hz Tone. Purple.", freqStart: 10, freqEnd: 10, duration: 1200, engine: 'tone-963', noise: 'none', strobe: 'center-purple', color: '#800080', man: { goal: "Pineal Stim", audio: "963Hz Tone", visual: "Purple Dot" } },
            'synesthesia': { name: "SYNESTHESIA", cat: "ESOTERIC", desc: "Colour/Freq Sweep.", freqStart: 200, freqEnd: 600, duration: 1200, engine: 'spectral', noise: 'none', strobe: 'sweep', color: 'sweep', man: { goal: "Cross-Wiring", audio: "Freq Sweep", visual: "Colour Sweep" } },
            'remote': { name: "REMOTE VIEWING", cat: "ESOTERIC", desc: "LFO Gate. Snow.", freqStart: 6, freqEnd: 6, duration: 1800, engine: 'noise-gate', noise: 'pink', strobe: 'snow', color: '#111111', man: { goal: "Coordinate Lock", audio: "LFO Gated Pink Noise", visual: "Static Snow" } },
            'dead': { name: "DEAD AIR", cat: "ESOTERIC", desc: "Silence. Hallucination.", freqStart: 0, freqEnd: 0, duration: 1800, engine: 'silence', noise: 'none', strobe: 'static', color: '#FF0000', man: { goal: "Deprivation", audio: "Silence", visual: "Red Ganzfeld" } }
        };

        